
namespace Gear_Store
{
    partial class Form_Brand
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form_Brand));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.label3 = new System.Windows.Forms.Label();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.btn_Quit = new System.Windows.Forms.Button();
            this.txtProdID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnDelBrand = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAddBrand = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnDelPCatg = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAddlPCatg = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuDataGridView2 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.label1 = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView2)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(39, 137);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(458, 355);
            this.bunifuDataGridView1.TabIndex = 0;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(35, 46);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(104, 21);
            this.label3.TabIndex = 73;
            this.label3.Text = "Brand Name:";
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // btn_Quit
            // 
            this.btn_Quit.BackColor = System.Drawing.Color.Transparent;
            this.btn_Quit.FlatAppearance.BorderSize = 0;
            this.btn_Quit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn_Quit.Image = ((System.Drawing.Image)(resources.GetObject("btn_Quit.Image")));
            this.btn_Quit.Location = new System.Drawing.Point(982, 4);
            this.btn_Quit.Margin = new System.Windows.Forms.Padding(4);
            this.btn_Quit.Name = "btn_Quit";
            this.btn_Quit.Size = new System.Drawing.Size(56, 51);
            this.btn_Quit.TabIndex = 75;
            this.btn_Quit.UseVisualStyleBackColor = false;
            // 
            // txtProdID
            // 
            this.txtProdID.AcceptsReturn = false;
            this.txtProdID.AcceptsTab = false;
            this.txtProdID.AnimationSpeed = 200;
            this.txtProdID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtProdID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtProdID.BackColor = System.Drawing.Color.Transparent;
            this.txtProdID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtProdID.BackgroundImage")));
            this.txtProdID.BorderColorActive = System.Drawing.Color.Orange;
            this.txtProdID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtProdID.BorderColorHover = System.Drawing.Color.Orange;
            this.txtProdID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtProdID.BorderRadius = 1;
            this.txtProdID.BorderThickness = 1;
            this.txtProdID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtProdID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProdID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtProdID.DefaultText = "";
            this.txtProdID.FillColor = System.Drawing.Color.White;
            this.txtProdID.ForeColor = System.Drawing.Color.Black;
            this.txtProdID.HideSelection = true;
            this.txtProdID.IconLeft = null;
            this.txtProdID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProdID.IconPadding = 10;
            this.txtProdID.IconRight = null;
            this.txtProdID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProdID.Lines = new string[0];
            this.txtProdID.Location = new System.Drawing.Point(39, 71);
            this.txtProdID.Margin = new System.Windows.Forms.Padding(4);
            this.txtProdID.MaxLength = 32767;
            this.txtProdID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtProdID.Modified = false;
            this.txtProdID.Multiline = false;
            this.txtProdID.Name = "txtProdID";
            stateProperties5.BorderColor = System.Drawing.Color.Orange;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProdID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtProdID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Orange;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProdID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProdID.OnIdleState = stateProperties8;
            this.txtProdID.Padding = new System.Windows.Forms.Padding(4);
            this.txtProdID.PasswordChar = '\0';
            this.txtProdID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProdID.PlaceholderText = "";
            this.txtProdID.ReadOnly = false;
            this.txtProdID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtProdID.SelectedText = "";
            this.txtProdID.SelectionLength = 0;
            this.txtProdID.SelectionStart = 0;
            this.txtProdID.ShortcutsEnabled = true;
            this.txtProdID.Size = new System.Drawing.Size(303, 40);
            this.txtProdID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtProdID.TabIndex = 74;
            this.txtProdID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtProdID.TextMarginBottom = 0;
            this.txtProdID.TextMarginLeft = 3;
            this.txtProdID.TextMarginTop = 0;
            this.txtProdID.TextPlaceholder = "";
            this.txtProdID.UseSystemPasswordChar = false;
            this.txtProdID.WordWrap = true;
            // 
            // btnDelBrand
            // 
            this.btnDelBrand.AllowAnimations = true;
            this.btnDelBrand.AllowMouseEffects = true;
            this.btnDelBrand.AllowToggling = false;
            this.btnDelBrand.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnDelBrand.AnimationSpeed = 200;
            this.btnDelBrand.AutoGenerateColors = false;
            this.btnDelBrand.AutoRoundBorders = false;
            this.btnDelBrand.AutoSizeLeftIcon = true;
            this.btnDelBrand.AutoSizeRightIcon = true;
            this.btnDelBrand.BackColor = System.Drawing.Color.Transparent;
            this.btnDelBrand.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelBrand.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelBrand.BackgroundImage")));
            this.btnDelBrand.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelBrand.ButtonText = "";
            this.btnDelBrand.ButtonTextMarginLeft = 0;
            this.btnDelBrand.ColorContrastOnClick = 45;
            this.btnDelBrand.ColorContrastOnHover = 45;
            this.btnDelBrand.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnDelBrand.CustomizableEdges = borderEdges3;
            this.btnDelBrand.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelBrand.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelBrand.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelBrand.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelBrand.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnDelBrand.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDelBrand.ForeColor = System.Drawing.Color.White;
            this.btnDelBrand.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDelBrand.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelBrand.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDelBrand.IconMarginLeft = 11;
            this.btnDelBrand.IconPadding = 10;
            this.btnDelBrand.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDelBrand.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelBrand.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDelBrand.IconSize = 25;
            this.btnDelBrand.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelBrand.IdleBorderRadius = 1;
            this.btnDelBrand.IdleBorderThickness = 1;
            this.btnDelBrand.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelBrand.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDelBrand.IdleIconLeftImage")));
            this.btnDelBrand.IdleIconRightImage = null;
            this.btnDelBrand.IndicateFocus = false;
            this.btnDelBrand.Location = new System.Drawing.Point(438, 71);
            this.btnDelBrand.Margin = new System.Windows.Forms.Padding(4);
            this.btnDelBrand.Name = "btnDelBrand";
            this.btnDelBrand.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelBrand.OnDisabledState.BorderRadius = 1;
            this.btnDelBrand.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelBrand.OnDisabledState.BorderThickness = 1;
            this.btnDelBrand.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelBrand.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelBrand.OnDisabledState.IconLeftImage = null;
            this.btnDelBrand.OnDisabledState.IconRightImage = null;
            this.btnDelBrand.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelBrand.onHoverState.BorderRadius = 1;
            this.btnDelBrand.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelBrand.onHoverState.BorderThickness = 1;
            this.btnDelBrand.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelBrand.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.btnDelBrand.onHoverState.IconLeftImage = null;
            this.btnDelBrand.onHoverState.IconRightImage = null;
            this.btnDelBrand.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelBrand.OnIdleState.BorderRadius = 1;
            this.btnDelBrand.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelBrand.OnIdleState.BorderThickness = 1;
            this.btnDelBrand.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelBrand.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDelBrand.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDel.OnIdleState.IconLeftImage")));
            this.btnDelBrand.OnIdleState.IconRightImage = null;
            this.btnDelBrand.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelBrand.OnPressedState.BorderRadius = 1;
            this.btnDelBrand.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelBrand.OnPressedState.BorderThickness = 1;
            this.btnDelBrand.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelBrand.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.btnDelBrand.OnPressedState.IconLeftImage = null;
            this.btnDelBrand.OnPressedState.IconRightImage = null;
            this.btnDelBrand.Size = new System.Drawing.Size(59, 48);
            this.btnDelBrand.TabIndex = 18;
            this.btnDelBrand.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelBrand.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDelBrand.TextMarginLeft = 0;
            this.btnDelBrand.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDelBrand.UseDefaultRadiusAndThickness = true;
            // 
            // btnAddBrand
            // 
            this.btnAddBrand.AllowAnimations = true;
            this.btnAddBrand.AllowMouseEffects = true;
            this.btnAddBrand.AllowToggling = false;
            this.btnAddBrand.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAddBrand.AnimationSpeed = 200;
            this.btnAddBrand.AutoGenerateColors = false;
            this.btnAddBrand.AutoRoundBorders = false;
            this.btnAddBrand.AutoSizeLeftIcon = true;
            this.btnAddBrand.AutoSizeRightIcon = true;
            this.btnAddBrand.BackColor = System.Drawing.Color.Transparent;
            this.btnAddBrand.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddBrand.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddBrand.BackgroundImage")));
            this.btnAddBrand.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddBrand.ButtonText = "";
            this.btnAddBrand.ButtonTextMarginLeft = 0;
            this.btnAddBrand.ColorContrastOnClick = 45;
            this.btnAddBrand.ColorContrastOnHover = 45;
            this.btnAddBrand.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnAddBrand.CustomizableEdges = borderEdges4;
            this.btnAddBrand.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddBrand.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddBrand.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddBrand.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddBrand.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnAddBrand.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddBrand.ForeColor = System.Drawing.Color.White;
            this.btnAddBrand.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddBrand.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddBrand.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddBrand.IconMarginLeft = 11;
            this.btnAddBrand.IconPadding = 10;
            this.btnAddBrand.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddBrand.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddBrand.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddBrand.IconSize = 25;
            this.btnAddBrand.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddBrand.IdleBorderRadius = 1;
            this.btnAddBrand.IdleBorderThickness = 1;
            this.btnAddBrand.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddBrand.IdleIconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.btnAddBrand.IdleIconRightImage = null;
            this.btnAddBrand.IndicateFocus = false;
            this.btnAddBrand.Location = new System.Drawing.Point(371, 71);
            this.btnAddBrand.Margin = new System.Windows.Forms.Padding(4);
            this.btnAddBrand.Name = "btnAddBrand";
            this.btnAddBrand.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddBrand.OnDisabledState.BorderRadius = 1;
            this.btnAddBrand.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddBrand.OnDisabledState.BorderThickness = 1;
            this.btnAddBrand.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddBrand.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddBrand.OnDisabledState.IconLeftImage = null;
            this.btnAddBrand.OnDisabledState.IconRightImage = null;
            this.btnAddBrand.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddBrand.onHoverState.BorderRadius = 1;
            this.btnAddBrand.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddBrand.onHoverState.BorderThickness = 1;
            this.btnAddBrand.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddBrand.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.btnAddBrand.onHoverState.IconLeftImage = null;
            this.btnAddBrand.onHoverState.IconRightImage = null;
            this.btnAddBrand.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddBrand.OnIdleState.BorderRadius = 1;
            this.btnAddBrand.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddBrand.OnIdleState.BorderThickness = 1;
            this.btnAddBrand.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddBrand.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddBrand.OnIdleState.IconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.btnAddBrand.OnIdleState.IconRightImage = null;
            this.btnAddBrand.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddBrand.OnPressedState.BorderRadius = 1;
            this.btnAddBrand.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddBrand.OnPressedState.BorderThickness = 1;
            this.btnAddBrand.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddBrand.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.btnAddBrand.OnPressedState.IconLeftImage = null;
            this.btnAddBrand.OnPressedState.IconRightImage = null;
            this.btnAddBrand.Size = new System.Drawing.Size(59, 48);
            this.btnAddBrand.TabIndex = 17;
            this.btnAddBrand.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddBrand.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddBrand.TextMarginLeft = 0;
            this.btnAddBrand.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddBrand.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.Orange;
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.Orange;
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox1.BorderRadius = 1;
            this.bunifuTextBox1.BorderThickness = 1;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox1.ForeColor = System.Drawing.Color.Black;
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            this.bunifuTextBox1.Location = new System.Drawing.Point(554, 71);
            this.bunifuTextBox1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties1.BorderColor = System.Drawing.Color.Orange;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Orange;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties4;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(4);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox1.PlaceholderText = "";
            this.bunifuTextBox1.ReadOnly = false;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(303, 40);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 79;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 0;
            this.bunifuTextBox1.TextPlaceholder = "";
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // btnDelPCatg
            // 
            this.btnDelPCatg.AllowAnimations = true;
            this.btnDelPCatg.AllowMouseEffects = true;
            this.btnDelPCatg.AllowToggling = false;
            this.btnDelPCatg.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnDelPCatg.AnimationSpeed = 200;
            this.btnDelPCatg.AutoGenerateColors = false;
            this.btnDelPCatg.AutoRoundBorders = false;
            this.btnDelPCatg.AutoSizeLeftIcon = true;
            this.btnDelPCatg.AutoSizeRightIcon = true;
            this.btnDelPCatg.BackColor = System.Drawing.Color.Transparent;
            this.btnDelPCatg.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelPCatg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelPCatg.BackgroundImage")));
            this.btnDelPCatg.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelPCatg.ButtonText = "";
            this.btnDelPCatg.ButtonTextMarginLeft = 0;
            this.btnDelPCatg.ColorContrastOnClick = 45;
            this.btnDelPCatg.ColorContrastOnHover = 45;
            this.btnDelPCatg.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnDelPCatg.CustomizableEdges = borderEdges1;
            this.btnDelPCatg.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelPCatg.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelPCatg.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelPCatg.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelPCatg.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnDelPCatg.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDelPCatg.ForeColor = System.Drawing.Color.White;
            this.btnDelPCatg.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDelPCatg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelPCatg.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDelPCatg.IconMarginLeft = 11;
            this.btnDelPCatg.IconPadding = 10;
            this.btnDelPCatg.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDelPCatg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelPCatg.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDelPCatg.IconSize = 25;
            this.btnDelPCatg.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelPCatg.IdleBorderRadius = 1;
            this.btnDelPCatg.IdleBorderThickness = 1;
            this.btnDelPCatg.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelPCatg.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDelPCatg.IdleIconLeftImage")));
            this.btnDelPCatg.IdleIconRightImage = null;
            this.btnDelPCatg.IndicateFocus = false;
            this.btnDelPCatg.Location = new System.Drawing.Point(953, 71);
            this.btnDelPCatg.Margin = new System.Windows.Forms.Padding(4);
            this.btnDelPCatg.Name = "btnDelPCatg";
            this.btnDelPCatg.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelPCatg.OnDisabledState.BorderRadius = 1;
            this.btnDelPCatg.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelPCatg.OnDisabledState.BorderThickness = 1;
            this.btnDelPCatg.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelPCatg.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelPCatg.OnDisabledState.IconLeftImage = null;
            this.btnDelPCatg.OnDisabledState.IconRightImage = null;
            this.btnDelPCatg.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelPCatg.onHoverState.BorderRadius = 1;
            this.btnDelPCatg.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelPCatg.onHoverState.BorderThickness = 1;
            this.btnDelPCatg.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelPCatg.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.btnDelPCatg.onHoverState.IconLeftImage = null;
            this.btnDelPCatg.onHoverState.IconRightImage = null;
            this.btnDelPCatg.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelPCatg.OnIdleState.BorderRadius = 1;
            this.btnDelPCatg.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelPCatg.OnIdleState.BorderThickness = 1;
            this.btnDelPCatg.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelPCatg.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDelPCatg.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
            this.btnDelPCatg.OnIdleState.IconRightImage = null;
            this.btnDelPCatg.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelPCatg.OnPressedState.BorderRadius = 1;
            this.btnDelPCatg.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelPCatg.OnPressedState.BorderThickness = 1;
            this.btnDelPCatg.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelPCatg.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.btnDelPCatg.OnPressedState.IconLeftImage = null;
            this.btnDelPCatg.OnPressedState.IconRightImage = null;
            this.btnDelPCatg.Size = new System.Drawing.Size(59, 48);
            this.btnDelPCatg.TabIndex = 78;
            this.btnDelPCatg.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelPCatg.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDelPCatg.TextMarginLeft = 0;
            this.btnDelPCatg.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDelPCatg.UseDefaultRadiusAndThickness = true;
            // 
            // btnAddlPCatg
            // 
            this.btnAddlPCatg.AllowAnimations = true;
            this.btnAddlPCatg.AllowMouseEffects = true;
            this.btnAddlPCatg.AllowToggling = false;
            this.btnAddlPCatg.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAddlPCatg.AnimationSpeed = 200;
            this.btnAddlPCatg.AutoGenerateColors = false;
            this.btnAddlPCatg.AutoRoundBorders = false;
            this.btnAddlPCatg.AutoSizeLeftIcon = true;
            this.btnAddlPCatg.AutoSizeRightIcon = true;
            this.btnAddlPCatg.BackColor = System.Drawing.Color.Transparent;
            this.btnAddlPCatg.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddlPCatg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddlPCatg.BackgroundImage")));
            this.btnAddlPCatg.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddlPCatg.ButtonText = "";
            this.btnAddlPCatg.ButtonTextMarginLeft = 0;
            this.btnAddlPCatg.ColorContrastOnClick = 45;
            this.btnAddlPCatg.ColorContrastOnHover = 45;
            this.btnAddlPCatg.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAddlPCatg.CustomizableEdges = borderEdges2;
            this.btnAddlPCatg.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddlPCatg.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddlPCatg.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddlPCatg.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddlPCatg.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnAddlPCatg.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddlPCatg.ForeColor = System.Drawing.Color.White;
            this.btnAddlPCatg.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddlPCatg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddlPCatg.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddlPCatg.IconMarginLeft = 11;
            this.btnAddlPCatg.IconPadding = 10;
            this.btnAddlPCatg.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddlPCatg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddlPCatg.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddlPCatg.IconSize = 25;
            this.btnAddlPCatg.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddlPCatg.IdleBorderRadius = 1;
            this.btnAddlPCatg.IdleBorderThickness = 1;
            this.btnAddlPCatg.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddlPCatg.IdleIconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.btnAddlPCatg.IdleIconRightImage = null;
            this.btnAddlPCatg.IndicateFocus = false;
            this.btnAddlPCatg.Location = new System.Drawing.Point(886, 71);
            this.btnAddlPCatg.Margin = new System.Windows.Forms.Padding(4);
            this.btnAddlPCatg.Name = "btnAddlPCatg";
            this.btnAddlPCatg.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddlPCatg.OnDisabledState.BorderRadius = 1;
            this.btnAddlPCatg.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddlPCatg.OnDisabledState.BorderThickness = 1;
            this.btnAddlPCatg.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddlPCatg.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddlPCatg.OnDisabledState.IconLeftImage = null;
            this.btnAddlPCatg.OnDisabledState.IconRightImage = null;
            this.btnAddlPCatg.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddlPCatg.onHoverState.BorderRadius = 1;
            this.btnAddlPCatg.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddlPCatg.onHoverState.BorderThickness = 1;
            this.btnAddlPCatg.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddlPCatg.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.btnAddlPCatg.onHoverState.IconLeftImage = null;
            this.btnAddlPCatg.onHoverState.IconRightImage = null;
            this.btnAddlPCatg.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddlPCatg.OnIdleState.BorderRadius = 1;
            this.btnAddlPCatg.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddlPCatg.OnIdleState.BorderThickness = 1;
            this.btnAddlPCatg.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddlPCatg.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddlPCatg.OnIdleState.IconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.btnAddlPCatg.OnIdleState.IconRightImage = null;
            this.btnAddlPCatg.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddlPCatg.OnPressedState.BorderRadius = 1;
            this.btnAddlPCatg.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddlPCatg.OnPressedState.BorderThickness = 1;
            this.btnAddlPCatg.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddlPCatg.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.btnAddlPCatg.OnPressedState.IconLeftImage = null;
            this.btnAddlPCatg.OnPressedState.IconRightImage = null;
            this.btnAddlPCatg.Size = new System.Drawing.Size(59, 48);
            this.btnAddlPCatg.TabIndex = 77;
            this.btnAddlPCatg.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddlPCatg.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddlPCatg.TextMarginLeft = 0;
            this.btnAddlPCatg.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddlPCatg.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuDataGridView2
            // 
            this.bunifuDataGridView2.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView2.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.bunifuDataGridView2.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView2.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView2.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView2.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.bunifuDataGridView2.ColumnHeadersHeight = 40;
            this.bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView2.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView2.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView2.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView2.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView2.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView2.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView2.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView2.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView2.CurrentTheme.Name = null;
            this.bunifuDataGridView2.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView2.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView2.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView2.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView2.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView2.DefaultCellStyle = dataGridViewCellStyle6;
            this.bunifuDataGridView2.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView2.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView2.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView2.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView2.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView2.Location = new System.Drawing.Point(554, 137);
            this.bunifuDataGridView2.Name = "bunifuDataGridView2";
            this.bunifuDataGridView2.RowHeadersVisible = false;
            this.bunifuDataGridView2.RowTemplate.Height = 40;
            this.bunifuDataGridView2.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView2.Size = new System.Drawing.Size(458, 355);
            this.bunifuDataGridView2.TabIndex = 76;
            this.bunifuDataGridView2.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(550, 46);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(144, 21);
            this.label1.TabIndex = 80;
            this.label1.Text = "Product Category:";
            // 
            // Form_Brand
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(42)))), ((int)(((byte)(45)))));
            this.ClientSize = new System.Drawing.Size(1051, 531);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.bunifuTextBox1);
            this.Controls.Add(this.btnDelPCatg);
            this.Controls.Add(this.btnAddlPCatg);
            this.Controls.Add(this.bunifuDataGridView2);
            this.Controls.Add(this.btn_Quit);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.txtProdID);
            this.Controls.Add(this.btnDelBrand);
            this.Controls.Add(this.btnAddBrand);
            this.Controls.Add(this.bunifuDataGridView1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form_Brand";
            this.Text = "Form_Brand";
            this.Load += new System.EventHandler(this.Form_Brand_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView2)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelBrand;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddBrand;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox txtProdID;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private System.Windows.Forms.Button btn_Quit;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelPCatg;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddlPCatg;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView2;
    }
}