
namespace Gear_Store
{
    partial class Form_ProductInfo
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form_ProductInfo));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panelTopBar = new System.Windows.Forms.Panel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btn_Quit = new System.Windows.Forms.Button();
            this.cbbBrandName = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cbbCategoryName = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.labelBrandName = new System.Windows.Forms.Label();
            this.labelCategoryName = new System.Windows.Forms.Label();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.labelProductName = new System.Windows.Forms.Label();
            this.labelPrice = new System.Windows.Forms.Label();
            this.labelModelYear = new System.Windows.Forms.Label();
            this.txtModelYear = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtProductName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelProductID = new System.Windows.Forms.Label();
            this.bunifuGroupBox3 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.pbProducImage = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btnAddImage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDashBoard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtProductID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.panelTopBar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.bunifuGroupBox2.SuspendLayout();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbProducImage)).BeginInit();
            this.SuspendLayout();
            // 
            // panelTopBar
            // 
            this.panelTopBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.panelTopBar.Controls.Add(this.bunifuLabel2);
            this.panelTopBar.Controls.Add(this.bunifuLabel1);
            this.panelTopBar.Controls.Add(this.bunifuPictureBox1);
            this.panelTopBar.Controls.Add(this.btn_Quit);
            this.panelTopBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTopBar.ForeColor = System.Drawing.Color.Black;
            this.panelTopBar.Location = new System.Drawing.Point(0, 0);
            this.panelTopBar.Name = "panelTopBar";
            this.panelTopBar.Size = new System.Drawing.Size(784, 35);
            this.panelTopBar.TabIndex = 3;
            this.panelTopBar.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panelTopBar_MouseDown);
            this.panelTopBar.MouseMove += new System.Windows.Forms.MouseEventHandler(this.panelTopBar_MouseMove);
            this.panelTopBar.MouseUp += new System.Windows.Forms.MouseEventHandler(this.panelTopBar_MouseUp);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(371, 8);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(39, 17);
            this.bunifuLabel2.TabIndex = 5;
            this.bunifuLabel2.Text = "Mode";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Orange;
            this.bunifuLabel1.Location = new System.Drawing.Point(61, 8);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(88, 17);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "Product Info";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = global::Gear_Store.Properties.Resources.Orange_laptop_48px;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(13, 2);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(30, 30);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 2;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // btn_Quit
            // 
            this.btn_Quit.Dock = System.Windows.Forms.DockStyle.Right;
            this.btn_Quit.FlatAppearance.BorderSize = 0;
            this.btn_Quit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn_Quit.Image = ((System.Drawing.Image)(resources.GetObject("btn_Quit.Image")));
            this.btn_Quit.Location = new System.Drawing.Point(725, 0);
            this.btn_Quit.Name = "btn_Quit";
            this.btn_Quit.Size = new System.Drawing.Size(59, 35);
            this.btn_Quit.TabIndex = 1;
            this.btn_Quit.UseVisualStyleBackColor = true;
            this.btn_Quit.Click += new System.EventHandler(this.btn_Quit_Click);
            // 
            // cbbBrandName
            // 
            this.cbbBrandName.BackColor = System.Drawing.Color.Transparent;
            this.cbbBrandName.BackgroundColor = System.Drawing.Color.White;
            this.cbbBrandName.BorderColor = System.Drawing.Color.Silver;
            this.cbbBrandName.BorderRadius = 1;
            this.cbbBrandName.Color = System.Drawing.Color.Silver;
            this.cbbBrandName.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbbBrandName.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbBrandName.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbbBrandName.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbBrandName.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbbBrandName.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbbBrandName.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbbBrandName.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbbBrandName.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbbBrandName.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbBrandName.FillDropDown = true;
            this.cbbBrandName.FillIndicator = false;
            this.cbbBrandName.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbbBrandName.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cbbBrandName.ForeColor = System.Drawing.Color.Black;
            this.cbbBrandName.FormattingEnabled = true;
            this.cbbBrandName.Icon = null;
            this.cbbBrandName.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbBrandName.IndicatorColor = System.Drawing.Color.Gray;
            this.cbbBrandName.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbBrandName.ItemBackColor = System.Drawing.Color.White;
            this.cbbBrandName.ItemBorderColor = System.Drawing.Color.White;
            this.cbbBrandName.ItemForeColor = System.Drawing.Color.Black;
            this.cbbBrandName.ItemHeight = 26;
            this.cbbBrandName.ItemHighLightColor = System.Drawing.Color.Orange;
            this.cbbBrandName.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbbBrandName.ItemTopMargin = 3;
            this.cbbBrandName.Location = new System.Drawing.Point(137, 38);
            this.cbbBrandName.Name = "cbbBrandName";
            this.cbbBrandName.Size = new System.Drawing.Size(187, 32);
            this.cbbBrandName.TabIndex = 4;
            this.cbbBrandName.Text = null;
            this.cbbBrandName.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbBrandName.TextLeftMargin = 5;
            this.cbbBrandName.Click += new System.EventHandler(this.txtColorChange_Click);
            this.cbbBrandName.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // cbbCategoryName
            // 
            this.cbbCategoryName.BackColor = System.Drawing.Color.Transparent;
            this.cbbCategoryName.BackgroundColor = System.Drawing.Color.White;
            this.cbbCategoryName.BorderColor = System.Drawing.Color.Silver;
            this.cbbCategoryName.BorderRadius = 1;
            this.cbbCategoryName.Color = System.Drawing.Color.Silver;
            this.cbbCategoryName.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbbCategoryName.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbCategoryName.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbbCategoryName.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbCategoryName.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbbCategoryName.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbbCategoryName.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbbCategoryName.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbbCategoryName.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbbCategoryName.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbCategoryName.FillDropDown = true;
            this.cbbCategoryName.FillIndicator = false;
            this.cbbCategoryName.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbbCategoryName.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cbbCategoryName.ForeColor = System.Drawing.Color.Black;
            this.cbbCategoryName.FormattingEnabled = true;
            this.cbbCategoryName.Icon = null;
            this.cbbCategoryName.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbCategoryName.IndicatorColor = System.Drawing.Color.Gray;
            this.cbbCategoryName.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbCategoryName.ItemBackColor = System.Drawing.Color.White;
            this.cbbCategoryName.ItemBorderColor = System.Drawing.Color.White;
            this.cbbCategoryName.ItemForeColor = System.Drawing.Color.Black;
            this.cbbCategoryName.ItemHeight = 26;
            this.cbbCategoryName.ItemHighLightColor = System.Drawing.Color.Orange;
            this.cbbCategoryName.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbbCategoryName.ItemTopMargin = 3;
            this.cbbCategoryName.Location = new System.Drawing.Point(137, 93);
            this.cbbCategoryName.Name = "cbbCategoryName";
            this.cbbCategoryName.Size = new System.Drawing.Size(187, 32);
            this.cbbCategoryName.TabIndex = 5;
            this.cbbCategoryName.Text = null;
            this.cbbCategoryName.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbCategoryName.TextLeftMargin = 5;
            this.cbbCategoryName.Click += new System.EventHandler(this.txtColorChange_Click);
            this.cbbCategoryName.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.bunifuButton2);
            this.bunifuGroupBox2.Controls.Add(this.bunifuButton1);
            this.bunifuGroupBox2.Controls.Add(this.cbbCategoryName);
            this.bunifuGroupBox2.Controls.Add(this.cbbBrandName);
            this.bunifuGroupBox2.Controls.Add(this.labelBrandName);
            this.bunifuGroupBox2.Controls.Add(this.labelCategoryName);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuGroupBox2.ForeColor = System.Drawing.Color.Orange;
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(21, 347);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(389, 153);
            this.bunifuGroupBox2.TabIndex = 69;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Brand and Category";
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges6;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bunifuButton2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.bunifuButton2.IdleBorderRadius = 1;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.bunifuButton2.IdleIconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(335, 89);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(44, 39);
            this.bunifuButton2.TabIndex = 78;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges7;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bunifuButton1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.bunifuButton1.IdleBorderRadius = 1;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.bunifuButton1.IdleIconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(335, 33);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(44, 39);
            this.bunifuButton1.TabIndex = 77;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // labelBrandName
            // 
            this.labelBrandName.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelBrandName.ForeColor = System.Drawing.Color.White;
            this.labelBrandName.Location = new System.Drawing.Point(24, 33);
            this.labelBrandName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelBrandName.Name = "labelBrandName";
            this.labelBrandName.Size = new System.Drawing.Size(95, 37);
            this.labelBrandName.TabIndex = 40;
            this.labelBrandName.Text = "Brand Name:";
            this.labelBrandName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelCategoryName
            // 
            this.labelCategoryName.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelCategoryName.ForeColor = System.Drawing.Color.White;
            this.labelCategoryName.Location = new System.Drawing.Point(24, 84);
            this.labelCategoryName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelCategoryName.Name = "labelCategoryName";
            this.labelCategoryName.Size = new System.Drawing.Size(95, 37);
            this.labelCategoryName.TabIndex = 41;
            this.labelCategoryName.Text = "Category Name:";
            this.labelCategoryName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.labelProductName);
            this.bunifuGroupBox1.Controls.Add(this.labelPrice);
            this.bunifuGroupBox1.Controls.Add(this.labelModelYear);
            this.bunifuGroupBox1.Controls.Add(this.txtModelYear);
            this.bunifuGroupBox1.Controls.Add(this.txtProductName);
            this.bunifuGroupBox1.Controls.Add(this.txtPrice);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.Orange;
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(21, 144);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(389, 187);
            this.bunifuGroupBox1.TabIndex = 70;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Basic Info";
            // 
            // labelProductName
            // 
            this.labelProductName.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelProductName.ForeColor = System.Drawing.Color.White;
            this.labelProductName.Location = new System.Drawing.Point(24, 28);
            this.labelProductName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelProductName.Name = "labelProductName";
            this.labelProductName.Size = new System.Drawing.Size(95, 37);
            this.labelProductName.TabIndex = 40;
            this.labelProductName.Text = "Product Name:";
            this.labelProductName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelPrice
            // 
            this.labelPrice.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelPrice.ForeColor = System.Drawing.Color.White;
            this.labelPrice.Location = new System.Drawing.Point(24, 130);
            this.labelPrice.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelPrice.Name = "labelPrice";
            this.labelPrice.Size = new System.Drawing.Size(69, 36);
            this.labelPrice.TabIndex = 42;
            this.labelPrice.Text = "Price:";
            this.labelPrice.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelModelYear
            // 
            this.labelModelYear.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelModelYear.ForeColor = System.Drawing.Color.White;
            this.labelModelYear.Location = new System.Drawing.Point(24, 79);
            this.labelModelYear.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelModelYear.Name = "labelModelYear";
            this.labelModelYear.Size = new System.Drawing.Size(95, 37);
            this.labelModelYear.TabIndex = 41;
            this.labelModelYear.Text = "Model Year:";
            this.labelModelYear.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // txtModelYear
            // 
            this.txtModelYear.AcceptsReturn = false;
            this.txtModelYear.AcceptsTab = false;
            this.txtModelYear.AnimationSpeed = 200;
            this.txtModelYear.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtModelYear.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtModelYear.BackColor = System.Drawing.Color.Transparent;
            this.txtModelYear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtModelYear.BackgroundImage")));
            this.txtModelYear.BorderColorActive = System.Drawing.Color.Orange;
            this.txtModelYear.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtModelYear.BorderColorHover = System.Drawing.Color.Orange;
            this.txtModelYear.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtModelYear.BorderRadius = 1;
            this.txtModelYear.BorderThickness = 1;
            this.txtModelYear.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtModelYear.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtModelYear.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtModelYear.DefaultText = "";
            this.txtModelYear.FillColor = System.Drawing.Color.White;
            this.txtModelYear.ForeColor = System.Drawing.Color.Black;
            this.txtModelYear.HideSelection = true;
            this.txtModelYear.IconLeft = null;
            this.txtModelYear.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtModelYear.IconPadding = 10;
            this.txtModelYear.IconRight = null;
            this.txtModelYear.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtModelYear.Lines = new string[0];
            this.txtModelYear.Location = new System.Drawing.Point(137, 79);
            this.txtModelYear.MaxLength = 32767;
            this.txtModelYear.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtModelYear.Modified = false;
            this.txtModelYear.Multiline = false;
            this.txtModelYear.Name = "txtModelYear";
            stateProperties17.BorderColor = System.Drawing.Color.Orange;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtModelYear.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtModelYear.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Orange;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtModelYear.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtModelYear.OnIdleState = stateProperties20;
            this.txtModelYear.Padding = new System.Windows.Forms.Padding(3);
            this.txtModelYear.PasswordChar = '\0';
            this.txtModelYear.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtModelYear.PlaceholderText = "";
            this.txtModelYear.ReadOnly = false;
            this.txtModelYear.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtModelYear.SelectedText = "";
            this.txtModelYear.SelectionLength = 0;
            this.txtModelYear.SelectionStart = 0;
            this.txtModelYear.ShortcutsEnabled = true;
            this.txtModelYear.Size = new System.Drawing.Size(223, 37);
            this.txtModelYear.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtModelYear.TabIndex = 60;
            this.txtModelYear.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtModelYear.TextMarginBottom = 0;
            this.txtModelYear.TextMarginLeft = 3;
            this.txtModelYear.TextMarginTop = 0;
            this.txtModelYear.TextPlaceholder = "";
            this.txtModelYear.UseSystemPasswordChar = false;
            this.txtModelYear.WordWrap = true;
            this.txtModelYear.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtModelYear.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // txtProductName
            // 
            this.txtProductName.AcceptsReturn = false;
            this.txtProductName.AcceptsTab = false;
            this.txtProductName.AnimationSpeed = 200;
            this.txtProductName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtProductName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtProductName.BackColor = System.Drawing.Color.Transparent;
            this.txtProductName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtProductName.BackgroundImage")));
            this.txtProductName.BorderColorActive = System.Drawing.Color.Orange;
            this.txtProductName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtProductName.BorderColorHover = System.Drawing.Color.Orange;
            this.txtProductName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtProductName.BorderRadius = 1;
            this.txtProductName.BorderThickness = 1;
            this.txtProductName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtProductName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtProductName.DefaultText = "";
            this.txtProductName.FillColor = System.Drawing.Color.White;
            this.txtProductName.ForeColor = System.Drawing.Color.Black;
            this.txtProductName.HideSelection = true;
            this.txtProductName.IconLeft = null;
            this.txtProductName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductName.IconPadding = 10;
            this.txtProductName.IconRight = null;
            this.txtProductName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductName.Lines = new string[0];
            this.txtProductName.Location = new System.Drawing.Point(137, 28);
            this.txtProductName.MaxLength = 32767;
            this.txtProductName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtProductName.Modified = false;
            this.txtProductName.Multiline = false;
            this.txtProductName.Name = "txtProductName";
            stateProperties21.BorderColor = System.Drawing.Color.Orange;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductName.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtProductName.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Orange;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductName.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductName.OnIdleState = stateProperties24;
            this.txtProductName.Padding = new System.Windows.Forms.Padding(3);
            this.txtProductName.PasswordChar = '\0';
            this.txtProductName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProductName.PlaceholderText = "";
            this.txtProductName.ReadOnly = false;
            this.txtProductName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtProductName.SelectedText = "";
            this.txtProductName.SelectionLength = 0;
            this.txtProductName.SelectionStart = 0;
            this.txtProductName.ShortcutsEnabled = true;
            this.txtProductName.Size = new System.Drawing.Size(223, 37);
            this.txtProductName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtProductName.TabIndex = 59;
            this.txtProductName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtProductName.TextMarginBottom = 0;
            this.txtProductName.TextMarginLeft = 3;
            this.txtProductName.TextMarginTop = 0;
            this.txtProductName.TextPlaceholder = "";
            this.txtProductName.UseSystemPasswordChar = false;
            this.txtProductName.WordWrap = true;
            this.txtProductName.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtProductName.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // txtPrice
            // 
            this.txtPrice.AcceptsReturn = false;
            this.txtPrice.AcceptsTab = false;
            this.txtPrice.AnimationSpeed = 200;
            this.txtPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrice.BackColor = System.Drawing.Color.Transparent;
            this.txtPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrice.BackgroundImage")));
            this.txtPrice.BorderColorActive = System.Drawing.Color.Orange;
            this.txtPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPrice.BorderColorHover = System.Drawing.Color.Orange;
            this.txtPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPrice.BorderRadius = 1;
            this.txtPrice.BorderThickness = 1;
            this.txtPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPrice.DefaultText = "";
            this.txtPrice.FillColor = System.Drawing.Color.White;
            this.txtPrice.ForeColor = System.Drawing.Color.Black;
            this.txtPrice.HideSelection = true;
            this.txtPrice.IconLeft = null;
            this.txtPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrice.IconPadding = 10;
            this.txtPrice.IconRight = null;
            this.txtPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrice.Lines = new string[0];
            this.txtPrice.Location = new System.Drawing.Point(137, 130);
            this.txtPrice.MaxLength = 32767;
            this.txtPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrice.Modified = false;
            this.txtPrice.Multiline = false;
            this.txtPrice.Name = "txtPrice";
            stateProperties25.BorderColor = System.Drawing.Color.Orange;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrice.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrice.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Orange;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrice.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Black;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrice.OnIdleState = stateProperties28;
            this.txtPrice.Padding = new System.Windows.Forms.Padding(3);
            this.txtPrice.PasswordChar = '\0';
            this.txtPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPrice.PlaceholderText = "";
            this.txtPrice.ReadOnly = false;
            this.txtPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrice.SelectedText = "";
            this.txtPrice.SelectionLength = 0;
            this.txtPrice.SelectionStart = 0;
            this.txtPrice.ShortcutsEnabled = true;
            this.txtPrice.Size = new System.Drawing.Size(223, 37);
            this.txtPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPrice.TabIndex = 61;
            this.txtPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrice.TextMarginBottom = 0;
            this.txtPrice.TextMarginLeft = 3;
            this.txtPrice.TextMarginTop = 0;
            this.txtPrice.TextPlaceholder = "";
            this.txtPrice.UseSystemPasswordChar = false;
            this.txtPrice.WordWrap = true;
            this.txtPrice.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtPrice.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // labelProductID
            // 
            this.labelProductID.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelProductID.ForeColor = System.Drawing.Color.White;
            this.labelProductID.Location = new System.Drawing.Point(44, 78);
            this.labelProductID.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelProductID.Name = "labelProductID";
            this.labelProductID.Size = new System.Drawing.Size(106, 37);
            this.labelProductID.TabIndex = 71;
            this.labelProductID.Text = "Product ID:";
            this.labelProductID.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // bunifuGroupBox3
            // 
            this.bunifuGroupBox3.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox3.BorderRadius = 1;
            this.bunifuGroupBox3.BorderThickness = 1;
            this.bunifuGroupBox3.Controls.Add(this.pbProducImage);
            this.bunifuGroupBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuGroupBox3.ForeColor = System.Drawing.Color.Orange;
            this.bunifuGroupBox3.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox3.LabelIndent = 10;
            this.bunifuGroupBox3.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox3.Location = new System.Drawing.Point(477, 51);
            this.bunifuGroupBox3.Name = "bunifuGroupBox3";
            this.bunifuGroupBox3.Size = new System.Drawing.Size(268, 280);
            this.bunifuGroupBox3.TabIndex = 73;
            this.bunifuGroupBox3.TabStop = false;
            this.bunifuGroupBox3.Text = "Product\'s Image";
            // 
            // pbProducImage
            // 
            this.pbProducImage.AllowFocused = false;
            this.pbProducImage.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pbProducImage.AutoSizeHeight = true;
            this.pbProducImage.BorderRadius = 0;
            this.pbProducImage.Image = ((System.Drawing.Image)(resources.GetObject("pbProducImage.Image")));
            this.pbProducImage.IsCircle = true;
            this.pbProducImage.Location = new System.Drawing.Point(22, 27);
            this.pbProducImage.Name = "pbProducImage";
            this.pbProducImage.Size = new System.Drawing.Size(225, 225);
            this.pbProducImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbProducImage.TabIndex = 0;
            this.pbProducImage.TabStop = false;
            this.pbProducImage.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // btnAddImage
            // 
            this.btnAddImage.AllowAnimations = true;
            this.btnAddImage.AllowMouseEffects = true;
            this.btnAddImage.AllowToggling = false;
            this.btnAddImage.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAddImage.AnimationSpeed = 200;
            this.btnAddImage.AutoGenerateColors = false;
            this.btnAddImage.AutoRoundBorders = false;
            this.btnAddImage.AutoSizeLeftIcon = true;
            this.btnAddImage.AutoSizeRightIcon = true;
            this.btnAddImage.BackColor = System.Drawing.Color.Transparent;
            this.btnAddImage.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddImage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddImage.BackgroundImage")));
            this.btnAddImage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddImage.ButtonText = "";
            this.btnAddImage.ButtonTextMarginLeft = 0;
            this.btnAddImage.ColorContrastOnClick = 45;
            this.btnAddImage.ColorContrastOnHover = 45;
            this.btnAddImage.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnAddImage.CustomizableEdges = borderEdges8;
            this.btnAddImage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddImage.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddImage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddImage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddImage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnAddImage.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddImage.ForeColor = System.Drawing.Color.White;
            this.btnAddImage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddImage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddImage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddImage.IconMarginLeft = 11;
            this.btnAddImage.IconPadding = 10;
            this.btnAddImage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddImage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddImage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddImage.IconSize = 25;
            this.btnAddImage.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddImage.IdleBorderRadius = 1;
            this.btnAddImage.IdleBorderThickness = 1;
            this.btnAddImage.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddImage.IdleIconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.btnAddImage.IdleIconRightImage = null;
            this.btnAddImage.IndicateFocus = false;
            this.btnAddImage.Location = new System.Drawing.Point(719, 315);
            this.btnAddImage.Name = "btnAddImage";
            this.btnAddImage.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddImage.OnDisabledState.BorderRadius = 1;
            this.btnAddImage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddImage.OnDisabledState.BorderThickness = 1;
            this.btnAddImage.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddImage.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddImage.OnDisabledState.IconLeftImage = null;
            this.btnAddImage.OnDisabledState.IconRightImage = null;
            this.btnAddImage.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddImage.onHoverState.BorderRadius = 1;
            this.btnAddImage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddImage.onHoverState.BorderThickness = 1;
            this.btnAddImage.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddImage.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.btnAddImage.onHoverState.IconLeftImage = null;
            this.btnAddImage.onHoverState.IconRightImage = null;
            this.btnAddImage.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddImage.OnIdleState.BorderRadius = 1;
            this.btnAddImage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddImage.OnIdleState.BorderThickness = 1;
            this.btnAddImage.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddImage.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddImage.OnIdleState.IconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.btnAddImage.OnIdleState.IconRightImage = null;
            this.btnAddImage.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddImage.OnPressedState.BorderRadius = 1;
            this.btnAddImage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddImage.OnPressedState.BorderThickness = 1;
            this.btnAddImage.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddImage.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.btnAddImage.OnPressedState.IconLeftImage = null;
            this.btnAddImage.OnPressedState.IconRightImage = null;
            this.btnAddImage.Size = new System.Drawing.Size(44, 39);
            this.btnAddImage.TabIndex = 76;
            this.btnAddImage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddImage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddImage.TextMarginLeft = 0;
            this.btnAddImage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddImage.UseDefaultRadiusAndThickness = true;
            this.btnAddImage.Click += new System.EventHandler(this.btnAddImage_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Cancel";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges9;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnCancel.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.IdleBorderRadius = 15;
            this.btnCancel.IdleBorderThickness = 1;
            this.btnCancel.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(627, 456);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 15;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.onHoverState.BorderRadius = 15;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.OnIdleState.BorderRadius = 15;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.OnPressedState.BorderRadius = 15;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(118, 44);
            this.btnCancel.TabIndex = 75;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            // 
            // btnDashBoard
            // 
            this.btnDashBoard.AllowAnimations = true;
            this.btnDashBoard.AllowMouseEffects = true;
            this.btnDashBoard.AllowToggling = false;
            this.btnDashBoard.AnimationSpeed = 200;
            this.btnDashBoard.AutoGenerateColors = false;
            this.btnDashBoard.AutoRoundBorders = false;
            this.btnDashBoard.AutoSizeLeftIcon = true;
            this.btnDashBoard.AutoSizeRightIcon = true;
            this.btnDashBoard.BackColor = System.Drawing.Color.Transparent;
            this.btnDashBoard.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDashBoard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDashBoard.BackgroundImage")));
            this.btnDashBoard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashBoard.ButtonText = "Save";
            this.btnDashBoard.ButtonTextMarginLeft = 0;
            this.btnDashBoard.ColorContrastOnClick = 45;
            this.btnDashBoard.ColorContrastOnHover = 45;
            this.btnDashBoard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btnDashBoard.CustomizableEdges = borderEdges10;
            this.btnDashBoard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDashBoard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashBoard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashBoard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashBoard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnDashBoard.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashBoard.ForeColor = System.Drawing.Color.White;
            this.btnDashBoard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashBoard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashBoard.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDashBoard.IconMarginLeft = 11;
            this.btnDashBoard.IconPadding = 10;
            this.btnDashBoard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDashBoard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashBoard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDashBoard.IconSize = 25;
            this.btnDashBoard.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDashBoard.IdleBorderRadius = 15;
            this.btnDashBoard.IdleBorderThickness = 1;
            this.btnDashBoard.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDashBoard.IdleIconLeftImage = null;
            this.btnDashBoard.IdleIconRightImage = null;
            this.btnDashBoard.IndicateFocus = false;
            this.btnDashBoard.Location = new System.Drawing.Point(499, 456);
            this.btnDashBoard.Name = "btnDashBoard";
            this.btnDashBoard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashBoard.OnDisabledState.BorderRadius = 15;
            this.btnDashBoard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashBoard.OnDisabledState.BorderThickness = 1;
            this.btnDashBoard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashBoard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashBoard.OnDisabledState.IconLeftImage = null;
            this.btnDashBoard.OnDisabledState.IconRightImage = null;
            this.btnDashBoard.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDashBoard.onHoverState.BorderRadius = 15;
            this.btnDashBoard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashBoard.onHoverState.BorderThickness = 1;
            this.btnDashBoard.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDashBoard.onHoverState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnDashBoard.onHoverState.IconLeftImage = null;
            this.btnDashBoard.onHoverState.IconRightImage = null;
            this.btnDashBoard.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDashBoard.OnIdleState.BorderRadius = 15;
            this.btnDashBoard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashBoard.OnIdleState.BorderThickness = 1;
            this.btnDashBoard.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDashBoard.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDashBoard.OnIdleState.IconLeftImage = null;
            this.btnDashBoard.OnIdleState.IconRightImage = null;
            this.btnDashBoard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDashBoard.OnPressedState.BorderRadius = 15;
            this.btnDashBoard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashBoard.OnPressedState.BorderThickness = 1;
            this.btnDashBoard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDashBoard.OnPressedState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnDashBoard.OnPressedState.IconLeftImage = null;
            this.btnDashBoard.OnPressedState.IconRightImage = null;
            this.btnDashBoard.Size = new System.Drawing.Size(118, 44);
            this.btnDashBoard.TabIndex = 74;
            this.btnDashBoard.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDashBoard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDashBoard.TextMarginLeft = 0;
            this.btnDashBoard.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDashBoard.UseDefaultRadiusAndThickness = true;
            // 
            // txtProductID
            // 
            this.txtProductID.AcceptsReturn = false;
            this.txtProductID.AcceptsTab = false;
            this.txtProductID.AnimationSpeed = 200;
            this.txtProductID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtProductID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtProductID.BackColor = System.Drawing.Color.Transparent;
            this.txtProductID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtProductID.BackgroundImage")));
            this.txtProductID.BorderColorActive = System.Drawing.Color.Orange;
            this.txtProductID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtProductID.BorderColorHover = System.Drawing.Color.Orange;
            this.txtProductID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtProductID.BorderRadius = 1;
            this.txtProductID.BorderThickness = 1;
            this.txtProductID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtProductID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtProductID.DefaultText = "";
            this.txtProductID.FillColor = System.Drawing.Color.White;
            this.txtProductID.ForeColor = System.Drawing.Color.Black;
            this.txtProductID.HideSelection = true;
            this.txtProductID.IconLeft = null;
            this.txtProductID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductID.IconPadding = 10;
            this.txtProductID.IconRight = null;
            this.txtProductID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductID.Lines = new string[0];
            this.txtProductID.Location = new System.Drawing.Point(158, 78);
            this.txtProductID.MaxLength = 32767;
            this.txtProductID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtProductID.Modified = false;
            this.txtProductID.Multiline = false;
            this.txtProductID.Name = "txtProductID";
            stateProperties29.BorderColor = System.Drawing.Color.Orange;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductID.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtProductID.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Orange;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductID.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Black;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductID.OnIdleState = stateProperties32;
            this.txtProductID.Padding = new System.Windows.Forms.Padding(3);
            this.txtProductID.PasswordChar = '\0';
            this.txtProductID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProductID.PlaceholderText = "";
            this.txtProductID.ReadOnly = false;
            this.txtProductID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtProductID.SelectedText = "";
            this.txtProductID.SelectionLength = 0;
            this.txtProductID.SelectionStart = 0;
            this.txtProductID.ShortcutsEnabled = true;
            this.txtProductID.Size = new System.Drawing.Size(223, 37);
            this.txtProductID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtProductID.TabIndex = 72;
            this.txtProductID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtProductID.TextMarginBottom = 0;
            this.txtProductID.TextMarginLeft = 3;
            this.txtProductID.TextMarginTop = 0;
            this.txtProductID.TextPlaceholder = "";
            this.txtProductID.UseSystemPasswordChar = false;
            this.txtProductID.WordWrap = true;
            this.txtProductID.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtProductID.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // Form_ProductInfo
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(42)))), ((int)(((byte)(45)))));
            this.ClientSize = new System.Drawing.Size(784, 530);
            this.Controls.Add(this.btnAddImage);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnDashBoard);
            this.Controls.Add(this.bunifuGroupBox3);
            this.Controls.Add(this.txtProductID);
            this.Controls.Add(this.labelProductID);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.panelTopBar);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form_ProductInfo";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Form_ProductInfo";
            this.Load += new System.EventHandler(this.Form_ProductInfo_Load);
            this.panelTopBar.ResumeLayout(false);
            this.panelTopBar.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbProducImage)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panelTopBar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.Button btn_Quit;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuDropdown cbbBrandName;
        private Bunifu.UI.WinForms.BunifuDropdown cbbCategoryName;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private System.Windows.Forms.Label labelBrandName;
        private System.Windows.Forms.Label labelCategoryName;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private System.Windows.Forms.Label labelProductName;
        private System.Windows.Forms.Label labelPrice;
        private System.Windows.Forms.Label labelModelYear;
        private Bunifu.UI.WinForms.BunifuTextBox txtModelYear;
        private Bunifu.UI.WinForms.BunifuTextBox txtProductName;
        private Bunifu.UI.WinForms.BunifuTextBox txtPrice;
        private Bunifu.UI.WinForms.BunifuTextBox txtProductID;
        private System.Windows.Forms.Label labelProductID;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDashBoard;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddImage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuPictureBox pbProducImage;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
    }
}