
namespace Gear_Store
{
    partial class Form_StaffDetails
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form_StaffDetails));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.labelStreet = new System.Windows.Forms.Label();
            this.labelCity = new System.Windows.Forms.Label();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.labelFName = new System.Windows.Forms.Label();
            this.labelEmail = new System.Windows.Forms.Label();
            this.labelPhone = new System.Windows.Forms.Label();
            this.labelLName = new System.Windows.Forms.Label();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.labelCustomerID = new System.Windows.Forms.Label();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.panelTopBar = new System.Windows.Forms.Panel();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtaddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtemail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtstaffid = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtpass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtusername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtsalary = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtbirthday = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnsave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btn_Quit = new System.Windows.Forms.Button();
            this.txtpoisition = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelState = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.txtphone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGroupBox2.SuspendLayout();
            this.bunifuGroupBox1.SuspendLayout();
            this.panelTopBar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.txtphone);
            this.bunifuGroupBox2.Controls.Add(this.label1);
            this.bunifuGroupBox2.Controls.Add(this.labelStreet);
            this.bunifuGroupBox2.Controls.Add(this.labelCity);
            this.bunifuGroupBox2.Controls.Add(this.txtaddress);
            this.bunifuGroupBox2.Controls.Add(this.txtemail);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuGroupBox2.ForeColor = System.Drawing.Color.Orange;
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(422, 137);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(366, 238);
            this.bunifuGroupBox2.TabIndex = 76;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Address";
            // 
            // labelStreet
            // 
            this.labelStreet.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelStreet.ForeColor = System.Drawing.Color.White;
            this.labelStreet.Location = new System.Drawing.Point(23, 41);
            this.labelStreet.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelStreet.Name = "labelStreet";
            this.labelStreet.Size = new System.Drawing.Size(69, 37);
            this.labelStreet.TabIndex = 44;
            this.labelStreet.Text = "Email:";
            this.labelStreet.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelCity
            // 
            this.labelCity.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelCity.ForeColor = System.Drawing.Color.White;
            this.labelCity.Location = new System.Drawing.Point(17, 97);
            this.labelCity.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelCity.Name = "labelCity";
            this.labelCity.Size = new System.Drawing.Size(75, 37);
            this.labelCity.TabIndex = 45;
            this.labelCity.Text = "Address:";
            this.labelCity.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.labelFName);
            this.bunifuGroupBox1.Controls.Add(this.labelEmail);
            this.bunifuGroupBox1.Controls.Add(this.labelPhone);
            this.bunifuGroupBox1.Controls.Add(this.labelLName);
            this.bunifuGroupBox1.Controls.Add(this.txtpass);
            this.bunifuGroupBox1.Controls.Add(this.txtusername);
            this.bunifuGroupBox1.Controls.Add(this.txtsalary);
            this.bunifuGroupBox1.Controls.Add(this.txtbirthday);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.Orange;
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(21, 137);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(389, 238);
            this.bunifuGroupBox1.TabIndex = 75;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Basic Info";
            // 
            // labelFName
            // 
            this.labelFName.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelFName.ForeColor = System.Drawing.Color.White;
            this.labelFName.Location = new System.Drawing.Point(24, 28);
            this.labelFName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelFName.Name = "labelFName";
            this.labelFName.Size = new System.Drawing.Size(95, 37);
            this.labelFName.TabIndex = 40;
            this.labelFName.Text = "User Name:";
            this.labelFName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelEmail
            // 
            this.labelEmail.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelEmail.ForeColor = System.Drawing.Color.White;
            this.labelEmail.Location = new System.Drawing.Point(24, 180);
            this.labelEmail.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelEmail.Name = "labelEmail";
            this.labelEmail.Size = new System.Drawing.Size(82, 37);
            this.labelEmail.TabIndex = 43;
            this.labelEmail.Text = "Salary:";
            this.labelEmail.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelPhone
            // 
            this.labelPhone.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelPhone.ForeColor = System.Drawing.Color.White;
            this.labelPhone.Location = new System.Drawing.Point(24, 130);
            this.labelPhone.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelPhone.Name = "labelPhone";
            this.labelPhone.Size = new System.Drawing.Size(82, 36);
            this.labelPhone.TabIndex = 42;
            this.labelPhone.Text = "Birthday:";
            this.labelPhone.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelLName
            // 
            this.labelLName.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelLName.ForeColor = System.Drawing.Color.White;
            this.labelLName.Location = new System.Drawing.Point(24, 79);
            this.labelLName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelLName.Name = "labelLName";
            this.labelLName.Size = new System.Drawing.Size(95, 37);
            this.labelLName.TabIndex = 41;
            this.labelLName.Text = "Password:";
            this.labelLName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // labelCustomerID
            // 
            this.labelCustomerID.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelCustomerID.ForeColor = System.Drawing.Color.White;
            this.labelCustomerID.Location = new System.Drawing.Point(21, 72);
            this.labelCustomerID.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelCustomerID.Name = "labelCustomerID";
            this.labelCustomerID.Size = new System.Drawing.Size(106, 37);
            this.labelCustomerID.TabIndex = 72;
            this.labelCustomerID.Text = "Staff ID:";
            this.labelCustomerID.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Orange;
            this.bunifuLabel1.Location = new System.Drawing.Point(61, 8);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(66, 17);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "Staff Info";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(371, 8);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(39, 17);
            this.bunifuLabel2.TabIndex = 4;
            this.bunifuLabel2.Text = "Mode";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // panelTopBar
            // 
            this.panelTopBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.panelTopBar.Controls.Add(this.bunifuLabel2);
            this.panelTopBar.Controls.Add(this.bunifuLabel1);
            this.panelTopBar.Controls.Add(this.bunifuPictureBox1);
            this.panelTopBar.Controls.Add(this.btn_Quit);
            this.panelTopBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTopBar.ForeColor = System.Drawing.Color.Black;
            this.panelTopBar.Location = new System.Drawing.Point(0, 0);
            this.panelTopBar.Name = "panelTopBar";
            this.panelTopBar.Size = new System.Drawing.Size(792, 35);
            this.panelTopBar.TabIndex = 71;
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Cancel";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges1;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnCancel.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.IdleBorderRadius = 15;
            this.btnCancel.IdleBorderThickness = 1;
            this.btnCancel.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(670, 394);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 15;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.onHoverState.BorderRadius = 15;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.OnIdleState.BorderRadius = 15;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.OnPressedState.BorderRadius = 15;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(118, 44);
            this.btnCancel.TabIndex = 77;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            // 
            // txtaddress
            // 
            this.txtaddress.AcceptsReturn = false;
            this.txtaddress.AcceptsTab = false;
            this.txtaddress.AnimationSpeed = 200;
            this.txtaddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtaddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtaddress.BackColor = System.Drawing.Color.Transparent;
            this.txtaddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtaddress.BackgroundImage")));
            this.txtaddress.BorderColorActive = System.Drawing.Color.Orange;
            this.txtaddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtaddress.BorderColorHover = System.Drawing.Color.Orange;
            this.txtaddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtaddress.BorderRadius = 1;
            this.txtaddress.BorderThickness = 1;
            this.txtaddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtaddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtaddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtaddress.DefaultText = "";
            this.txtaddress.FillColor = System.Drawing.Color.White;
            this.txtaddress.ForeColor = System.Drawing.Color.Black;
            this.txtaddress.HideSelection = true;
            this.txtaddress.IconLeft = null;
            this.txtaddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtaddress.IconPadding = 10;
            this.txtaddress.IconRight = null;
            this.txtaddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtaddress.Lines = new string[0];
            this.txtaddress.Location = new System.Drawing.Point(99, 97);
            this.txtaddress.MaxLength = 32767;
            this.txtaddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtaddress.Modified = false;
            this.txtaddress.Multiline = false;
            this.txtaddress.Name = "txtaddress";
            stateProperties5.BorderColor = System.Drawing.Color.Orange;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtaddress.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtaddress.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Orange;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtaddress.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtaddress.OnIdleState = stateProperties8;
            this.txtaddress.Padding = new System.Windows.Forms.Padding(3);
            this.txtaddress.PasswordChar = '\0';
            this.txtaddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtaddress.PlaceholderText = "";
            this.txtaddress.ReadOnly = false;
            this.txtaddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtaddress.SelectedText = "";
            this.txtaddress.SelectionLength = 0;
            this.txtaddress.SelectionStart = 0;
            this.txtaddress.ShortcutsEnabled = true;
            this.txtaddress.Size = new System.Drawing.Size(223, 37);
            this.txtaddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtaddress.TabIndex = 64;
            this.txtaddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtaddress.TextMarginBottom = 0;
            this.txtaddress.TextMarginLeft = 3;
            this.txtaddress.TextMarginTop = 0;
            this.txtaddress.TextPlaceholder = "";
            this.txtaddress.UseSystemPasswordChar = false;
            this.txtaddress.WordWrap = true;
            // 
            // txtemail
            // 
            this.txtemail.AcceptsReturn = false;
            this.txtemail.AcceptsTab = false;
            this.txtemail.AnimationSpeed = 200;
            this.txtemail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtemail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtemail.BackColor = System.Drawing.Color.Transparent;
            this.txtemail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtemail.BackgroundImage")));
            this.txtemail.BorderColorActive = System.Drawing.Color.Orange;
            this.txtemail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtemail.BorderColorHover = System.Drawing.Color.Orange;
            this.txtemail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtemail.BorderRadius = 1;
            this.txtemail.BorderThickness = 1;
            this.txtemail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtemail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtemail.DefaultText = "";
            this.txtemail.FillColor = System.Drawing.Color.White;
            this.txtemail.ForeColor = System.Drawing.Color.Black;
            this.txtemail.HideSelection = true;
            this.txtemail.IconLeft = null;
            this.txtemail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.IconPadding = 10;
            this.txtemail.IconRight = null;
            this.txtemail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.Lines = new string[0];
            this.txtemail.Location = new System.Drawing.Point(99, 41);
            this.txtemail.MaxLength = 32767;
            this.txtemail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtemail.Modified = false;
            this.txtemail.Multiline = false;
            this.txtemail.Name = "txtemail";
            stateProperties9.BorderColor = System.Drawing.Color.Orange;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtemail.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Orange;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnIdleState = stateProperties12;
            this.txtemail.Padding = new System.Windows.Forms.Padding(3);
            this.txtemail.PasswordChar = '\0';
            this.txtemail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtemail.PlaceholderText = "";
            this.txtemail.ReadOnly = false;
            this.txtemail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtemail.SelectedText = "";
            this.txtemail.SelectionLength = 0;
            this.txtemail.SelectionStart = 0;
            this.txtemail.ShortcutsEnabled = true;
            this.txtemail.Size = new System.Drawing.Size(223, 37);
            this.txtemail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtemail.TabIndex = 63;
            this.txtemail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtemail.TextMarginBottom = 0;
            this.txtemail.TextMarginLeft = 3;
            this.txtemail.TextMarginTop = 0;
            this.txtemail.TextPlaceholder = "";
            this.txtemail.UseSystemPasswordChar = false;
            this.txtemail.WordWrap = true;
            // 
            // txtstaffid
            // 
            this.txtstaffid.AcceptsReturn = false;
            this.txtstaffid.AcceptsTab = false;
            this.txtstaffid.AnimationSpeed = 200;
            this.txtstaffid.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtstaffid.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtstaffid.BackColor = System.Drawing.Color.Transparent;
            this.txtstaffid.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtstaffid.BackgroundImage")));
            this.txtstaffid.BorderColorActive = System.Drawing.Color.Orange;
            this.txtstaffid.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtstaffid.BorderColorHover = System.Drawing.Color.Orange;
            this.txtstaffid.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtstaffid.BorderRadius = 1;
            this.txtstaffid.BorderThickness = 1;
            this.txtstaffid.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtstaffid.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtstaffid.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtstaffid.DefaultText = "";
            this.txtstaffid.FillColor = System.Drawing.Color.White;
            this.txtstaffid.ForeColor = System.Drawing.Color.Black;
            this.txtstaffid.HideSelection = true;
            this.txtstaffid.IconLeft = null;
            this.txtstaffid.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtstaffid.IconPadding = 10;
            this.txtstaffid.IconRight = null;
            this.txtstaffid.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtstaffid.Lines = new string[0];
            this.txtstaffid.Location = new System.Drawing.Point(90, 72);
            this.txtstaffid.MaxLength = 32767;
            this.txtstaffid.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtstaffid.Modified = false;
            this.txtstaffid.Multiline = false;
            this.txtstaffid.Name = "txtstaffid";
            stateProperties33.BorderColor = System.Drawing.Color.Orange;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtstaffid.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtstaffid.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.Orange;
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtstaffid.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Black;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtstaffid.OnIdleState = stateProperties36;
            this.txtstaffid.Padding = new System.Windows.Forms.Padding(3);
            this.txtstaffid.PasswordChar = '\0';
            this.txtstaffid.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtstaffid.PlaceholderText = "";
            this.txtstaffid.ReadOnly = false;
            this.txtstaffid.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtstaffid.SelectedText = "";
            this.txtstaffid.SelectionLength = 0;
            this.txtstaffid.SelectionStart = 0;
            this.txtstaffid.ShortcutsEnabled = true;
            this.txtstaffid.Size = new System.Drawing.Size(223, 37);
            this.txtstaffid.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtstaffid.TabIndex = 73;
            this.txtstaffid.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtstaffid.TextMarginBottom = 0;
            this.txtstaffid.TextMarginLeft = 3;
            this.txtstaffid.TextMarginTop = 0;
            this.txtstaffid.TextPlaceholder = "";
            this.txtstaffid.UseSystemPasswordChar = false;
            this.txtstaffid.WordWrap = true;
            // 
            // txtpass
            // 
            this.txtpass.AcceptsReturn = false;
            this.txtpass.AcceptsTab = false;
            this.txtpass.AnimationSpeed = 200;
            this.txtpass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtpass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtpass.BackColor = System.Drawing.Color.Transparent;
            this.txtpass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtpass.BackgroundImage")));
            this.txtpass.BorderColorActive = System.Drawing.Color.Orange;
            this.txtpass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtpass.BorderColorHover = System.Drawing.Color.Orange;
            this.txtpass.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtpass.BorderRadius = 1;
            this.txtpass.BorderThickness = 1;
            this.txtpass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtpass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpass.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtpass.DefaultText = "";
            this.txtpass.FillColor = System.Drawing.Color.White;
            this.txtpass.ForeColor = System.Drawing.Color.Black;
            this.txtpass.HideSelection = true;
            this.txtpass.IconLeft = null;
            this.txtpass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpass.IconPadding = 10;
            this.txtpass.IconRight = null;
            this.txtpass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpass.Lines = new string[0];
            this.txtpass.Location = new System.Drawing.Point(137, 79);
            this.txtpass.MaxLength = 32767;
            this.txtpass.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtpass.Modified = false;
            this.txtpass.Multiline = false;
            this.txtpass.Name = "txtpass";
            stateProperties13.BorderColor = System.Drawing.Color.Orange;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpass.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtpass.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Orange;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpass.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpass.OnIdleState = stateProperties16;
            this.txtpass.Padding = new System.Windows.Forms.Padding(3);
            this.txtpass.PasswordChar = '\0';
            this.txtpass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtpass.PlaceholderText = "";
            this.txtpass.ReadOnly = false;
            this.txtpass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtpass.SelectedText = "";
            this.txtpass.SelectionLength = 0;
            this.txtpass.SelectionStart = 0;
            this.txtpass.ShortcutsEnabled = true;
            this.txtpass.Size = new System.Drawing.Size(223, 37);
            this.txtpass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtpass.TabIndex = 60;
            this.txtpass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtpass.TextMarginBottom = 0;
            this.txtpass.TextMarginLeft = 3;
            this.txtpass.TextMarginTop = 0;
            this.txtpass.TextPlaceholder = "";
            this.txtpass.UseSystemPasswordChar = false;
            this.txtpass.WordWrap = true;
            // 
            // txtusername
            // 
            this.txtusername.AcceptsReturn = false;
            this.txtusername.AcceptsTab = false;
            this.txtusername.AnimationSpeed = 200;
            this.txtusername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtusername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtusername.BackColor = System.Drawing.Color.Transparent;
            this.txtusername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtusername.BackgroundImage")));
            this.txtusername.BorderColorActive = System.Drawing.Color.Orange;
            this.txtusername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtusername.BorderColorHover = System.Drawing.Color.Orange;
            this.txtusername.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtusername.BorderRadius = 1;
            this.txtusername.BorderThickness = 1;
            this.txtusername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtusername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtusername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtusername.DefaultText = "";
            this.txtusername.FillColor = System.Drawing.Color.White;
            this.txtusername.ForeColor = System.Drawing.Color.Black;
            this.txtusername.HideSelection = true;
            this.txtusername.IconLeft = null;
            this.txtusername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtusername.IconPadding = 10;
            this.txtusername.IconRight = null;
            this.txtusername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtusername.Lines = new string[0];
            this.txtusername.Location = new System.Drawing.Point(137, 28);
            this.txtusername.MaxLength = 32767;
            this.txtusername.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtusername.Modified = false;
            this.txtusername.Multiline = false;
            this.txtusername.Name = "txtusername";
            stateProperties17.BorderColor = System.Drawing.Color.Orange;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtusername.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtusername.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Orange;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtusername.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtusername.OnIdleState = stateProperties20;
            this.txtusername.Padding = new System.Windows.Forms.Padding(3);
            this.txtusername.PasswordChar = '\0';
            this.txtusername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtusername.PlaceholderText = "";
            this.txtusername.ReadOnly = false;
            this.txtusername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtusername.SelectedText = "";
            this.txtusername.SelectionLength = 0;
            this.txtusername.SelectionStart = 0;
            this.txtusername.ShortcutsEnabled = true;
            this.txtusername.Size = new System.Drawing.Size(223, 37);
            this.txtusername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtusername.TabIndex = 59;
            this.txtusername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtusername.TextMarginBottom = 0;
            this.txtusername.TextMarginLeft = 3;
            this.txtusername.TextMarginTop = 0;
            this.txtusername.TextPlaceholder = "";
            this.txtusername.UseSystemPasswordChar = false;
            this.txtusername.WordWrap = true;
            // 
            // txtsalary
            // 
            this.txtsalary.AcceptsReturn = false;
            this.txtsalary.AcceptsTab = false;
            this.txtsalary.AnimationSpeed = 200;
            this.txtsalary.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtsalary.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtsalary.BackColor = System.Drawing.Color.Transparent;
            this.txtsalary.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtsalary.BackgroundImage")));
            this.txtsalary.BorderColorActive = System.Drawing.Color.Orange;
            this.txtsalary.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtsalary.BorderColorHover = System.Drawing.Color.Orange;
            this.txtsalary.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtsalary.BorderRadius = 1;
            this.txtsalary.BorderThickness = 1;
            this.txtsalary.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtsalary.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsalary.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtsalary.DefaultText = "";
            this.txtsalary.FillColor = System.Drawing.Color.White;
            this.txtsalary.ForeColor = System.Drawing.Color.Black;
            this.txtsalary.HideSelection = true;
            this.txtsalary.IconLeft = null;
            this.txtsalary.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsalary.IconPadding = 10;
            this.txtsalary.IconRight = null;
            this.txtsalary.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsalary.Lines = new string[0];
            this.txtsalary.Location = new System.Drawing.Point(138, 180);
            this.txtsalary.MaxLength = 32767;
            this.txtsalary.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtsalary.Modified = false;
            this.txtsalary.Multiline = false;
            this.txtsalary.Name = "txtsalary";
            stateProperties21.BorderColor = System.Drawing.Color.Orange;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsalary.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtsalary.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Orange;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsalary.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsalary.OnIdleState = stateProperties24;
            this.txtsalary.Padding = new System.Windows.Forms.Padding(3);
            this.txtsalary.PasswordChar = '\0';
            this.txtsalary.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtsalary.PlaceholderText = "";
            this.txtsalary.ReadOnly = false;
            this.txtsalary.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtsalary.SelectedText = "";
            this.txtsalary.SelectionLength = 0;
            this.txtsalary.SelectionStart = 0;
            this.txtsalary.ShortcutsEnabled = true;
            this.txtsalary.Size = new System.Drawing.Size(223, 37);
            this.txtsalary.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtsalary.TabIndex = 62;
            this.txtsalary.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtsalary.TextMarginBottom = 0;
            this.txtsalary.TextMarginLeft = 3;
            this.txtsalary.TextMarginTop = 0;
            this.txtsalary.TextPlaceholder = "";
            this.txtsalary.UseSystemPasswordChar = false;
            this.txtsalary.WordWrap = true;
            // 
            // txtbirthday
            // 
            this.txtbirthday.AcceptsReturn = false;
            this.txtbirthday.AcceptsTab = false;
            this.txtbirthday.AnimationSpeed = 200;
            this.txtbirthday.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtbirthday.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtbirthday.BackColor = System.Drawing.Color.Transparent;
            this.txtbirthday.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtbirthday.BackgroundImage")));
            this.txtbirthday.BorderColorActive = System.Drawing.Color.Orange;
            this.txtbirthday.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtbirthday.BorderColorHover = System.Drawing.Color.Orange;
            this.txtbirthday.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtbirthday.BorderRadius = 1;
            this.txtbirthday.BorderThickness = 1;
            this.txtbirthday.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtbirthday.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbirthday.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtbirthday.DefaultText = "";
            this.txtbirthday.FillColor = System.Drawing.Color.White;
            this.txtbirthday.ForeColor = System.Drawing.Color.Black;
            this.txtbirthday.HideSelection = true;
            this.txtbirthday.IconLeft = null;
            this.txtbirthday.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbirthday.IconPadding = 10;
            this.txtbirthday.IconRight = null;
            this.txtbirthday.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbirthday.Lines = new string[0];
            this.txtbirthday.Location = new System.Drawing.Point(137, 130);
            this.txtbirthday.MaxLength = 32767;
            this.txtbirthday.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtbirthday.Modified = false;
            this.txtbirthday.Multiline = false;
            this.txtbirthday.Name = "txtbirthday";
            stateProperties25.BorderColor = System.Drawing.Color.Orange;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbirthday.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtbirthday.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Orange;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbirthday.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Black;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbirthday.OnIdleState = stateProperties28;
            this.txtbirthday.Padding = new System.Windows.Forms.Padding(3);
            this.txtbirthday.PasswordChar = '\0';
            this.txtbirthday.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtbirthday.PlaceholderText = "";
            this.txtbirthday.ReadOnly = false;
            this.txtbirthday.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtbirthday.SelectedText = "";
            this.txtbirthday.SelectionLength = 0;
            this.txtbirthday.SelectionStart = 0;
            this.txtbirthday.ShortcutsEnabled = true;
            this.txtbirthday.Size = new System.Drawing.Size(223, 37);
            this.txtbirthday.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtbirthday.TabIndex = 61;
            this.txtbirthday.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtbirthday.TextMarginBottom = 0;
            this.txtbirthday.TextMarginLeft = 3;
            this.txtbirthday.TextMarginTop = 0;
            this.txtbirthday.TextPlaceholder = "";
            this.txtbirthday.UseSystemPasswordChar = false;
            this.txtbirthday.WordWrap = true;
            // 
            // btnsave
            // 
            this.btnsave.AllowAnimations = true;
            this.btnsave.AllowMouseEffects = true;
            this.btnsave.AllowToggling = false;
            this.btnsave.AnimationSpeed = 200;
            this.btnsave.AutoGenerateColors = false;
            this.btnsave.AutoRoundBorders = false;
            this.btnsave.AutoSizeLeftIcon = true;
            this.btnsave.AutoSizeRightIcon = true;
            this.btnsave.BackColor = System.Drawing.Color.Transparent;
            this.btnsave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnsave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnsave.BackgroundImage")));
            this.btnsave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.ButtonText = "Save";
            this.btnsave.ButtonTextMarginLeft = 0;
            this.btnsave.ColorContrastOnClick = 45;
            this.btnsave.ColorContrastOnHover = 45;
            this.btnsave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnsave.CustomizableEdges = borderEdges2;
            this.btnsave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnsave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnsave.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnsave.ForeColor = System.Drawing.Color.White;
            this.btnsave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnsave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnsave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnsave.IconMarginLeft = 11;
            this.btnsave.IconPadding = 10;
            this.btnsave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnsave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnsave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnsave.IconSize = 25;
            this.btnsave.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnsave.IdleBorderRadius = 15;
            this.btnsave.IdleBorderThickness = 1;
            this.btnsave.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnsave.IdleIconLeftImage = null;
            this.btnsave.IdleIconRightImage = null;
            this.btnsave.IndicateFocus = false;
            this.btnsave.Location = new System.Drawing.Point(527, 394);
            this.btnsave.Name = "btnsave";
            this.btnsave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsave.OnDisabledState.BorderRadius = 15;
            this.btnsave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.OnDisabledState.BorderThickness = 1;
            this.btnsave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsave.OnDisabledState.IconLeftImage = null;
            this.btnsave.OnDisabledState.IconRightImage = null;
            this.btnsave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnsave.onHoverState.BorderRadius = 15;
            this.btnsave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.onHoverState.BorderThickness = 1;
            this.btnsave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnsave.onHoverState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnsave.onHoverState.IconLeftImage = null;
            this.btnsave.onHoverState.IconRightImage = null;
            this.btnsave.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnsave.OnIdleState.BorderRadius = 15;
            this.btnsave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.OnIdleState.BorderThickness = 1;
            this.btnsave.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnsave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnsave.OnIdleState.IconLeftImage = null;
            this.btnsave.OnIdleState.IconRightImage = null;
            this.btnsave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnsave.OnPressedState.BorderRadius = 15;
            this.btnsave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.OnPressedState.BorderThickness = 1;
            this.btnsave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnsave.OnPressedState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnsave.OnPressedState.IconLeftImage = null;
            this.btnsave.OnPressedState.IconRightImage = null;
            this.btnsave.Size = new System.Drawing.Size(118, 44);
            this.btnsave.TabIndex = 74;
            this.btnsave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnsave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnsave.TextMarginLeft = 0;
            this.btnsave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnsave.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = global::Gear_Store.Properties.Resources.Orange_people_48px;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(8, 2);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(30, 30);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 2;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // btn_Quit
            // 
            this.btn_Quit.Dock = System.Windows.Forms.DockStyle.Right;
            this.btn_Quit.FlatAppearance.BorderSize = 0;
            this.btn_Quit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn_Quit.Image = ((System.Drawing.Image)(resources.GetObject("btn_Quit.Image")));
            this.btn_Quit.Location = new System.Drawing.Point(733, 0);
            this.btn_Quit.Name = "btn_Quit";
            this.btn_Quit.Size = new System.Drawing.Size(59, 35);
            this.btn_Quit.TabIndex = 1;
            this.btn_Quit.UseVisualStyleBackColor = true;
            // 
            // txtpoisition
            // 
            this.txtpoisition.AcceptsReturn = false;
            this.txtpoisition.AcceptsTab = false;
            this.txtpoisition.AnimationSpeed = 200;
            this.txtpoisition.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtpoisition.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtpoisition.BackColor = System.Drawing.Color.Transparent;
            this.txtpoisition.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtpoisition.BackgroundImage")));
            this.txtpoisition.BorderColorActive = System.Drawing.Color.Orange;
            this.txtpoisition.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtpoisition.BorderColorHover = System.Drawing.Color.Orange;
            this.txtpoisition.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtpoisition.BorderRadius = 1;
            this.txtpoisition.BorderThickness = 1;
            this.txtpoisition.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtpoisition.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpoisition.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtpoisition.DefaultText = "";
            this.txtpoisition.FillColor = System.Drawing.Color.White;
            this.txtpoisition.ForeColor = System.Drawing.Color.Black;
            this.txtpoisition.HideSelection = true;
            this.txtpoisition.IconLeft = null;
            this.txtpoisition.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpoisition.IconPadding = 10;
            this.txtpoisition.IconRight = null;
            this.txtpoisition.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpoisition.Lines = new string[0];
            this.txtpoisition.Location = new System.Drawing.Point(510, 72);
            this.txtpoisition.MaxLength = 32767;
            this.txtpoisition.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtpoisition.Modified = false;
            this.txtpoisition.Multiline = false;
            this.txtpoisition.Name = "txtpoisition";
            stateProperties29.BorderColor = System.Drawing.Color.Orange;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpoisition.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtpoisition.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Orange;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpoisition.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Black;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpoisition.OnIdleState = stateProperties32;
            this.txtpoisition.Padding = new System.Windows.Forms.Padding(3);
            this.txtpoisition.PasswordChar = '\0';
            this.txtpoisition.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtpoisition.PlaceholderText = "";
            this.txtpoisition.ReadOnly = false;
            this.txtpoisition.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtpoisition.SelectedText = "";
            this.txtpoisition.SelectionLength = 0;
            this.txtpoisition.SelectionStart = 0;
            this.txtpoisition.ShortcutsEnabled = true;
            this.txtpoisition.Size = new System.Drawing.Size(223, 37);
            this.txtpoisition.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtpoisition.TabIndex = 78;
            this.txtpoisition.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtpoisition.TextMarginBottom = 0;
            this.txtpoisition.TextMarginLeft = 3;
            this.txtpoisition.TextMarginTop = 0;
            this.txtpoisition.TextPlaceholder = "";
            this.txtpoisition.UseSystemPasswordChar = false;
            this.txtpoisition.WordWrap = true;
            // 
            // labelState
            // 
            this.labelState.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelState.ForeColor = System.Drawing.Color.White;
            this.labelState.Location = new System.Drawing.Point(419, 72);
            this.labelState.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelState.Name = "labelState";
            this.labelState.Size = new System.Drawing.Size(84, 37);
            this.labelState.TabIndex = 79;
            this.labelState.Text = "Poitision:";
            this.labelState.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label1
            // 
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(23, 157);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(64, 37);
            this.label1.TabIndex = 65;
            this.label1.Text = "Phone:";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // txtphone
            // 
            this.txtphone.AcceptsReturn = false;
            this.txtphone.AcceptsTab = false;
            this.txtphone.AnimationSpeed = 200;
            this.txtphone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtphone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtphone.BackColor = System.Drawing.Color.Transparent;
            this.txtphone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtphone.BackgroundImage")));
            this.txtphone.BorderColorActive = System.Drawing.Color.Orange;
            this.txtphone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtphone.BorderColorHover = System.Drawing.Color.Orange;
            this.txtphone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtphone.BorderRadius = 1;
            this.txtphone.BorderThickness = 1;
            this.txtphone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtphone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtphone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtphone.DefaultText = "";
            this.txtphone.FillColor = System.Drawing.Color.White;
            this.txtphone.ForeColor = System.Drawing.Color.Black;
            this.txtphone.HideSelection = true;
            this.txtphone.IconLeft = null;
            this.txtphone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtphone.IconPadding = 10;
            this.txtphone.IconRight = null;
            this.txtphone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtphone.Lines = new string[0];
            this.txtphone.Location = new System.Drawing.Point(99, 157);
            this.txtphone.MaxLength = 32767;
            this.txtphone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtphone.Modified = false;
            this.txtphone.Multiline = false;
            this.txtphone.Name = "txtphone";
            stateProperties1.BorderColor = System.Drawing.Color.Orange;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtphone.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtphone.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Orange;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtphone.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtphone.OnIdleState = stateProperties4;
            this.txtphone.Padding = new System.Windows.Forms.Padding(3);
            this.txtphone.PasswordChar = '\0';
            this.txtphone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtphone.PlaceholderText = "";
            this.txtphone.ReadOnly = false;
            this.txtphone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtphone.SelectedText = "";
            this.txtphone.SelectionLength = 0;
            this.txtphone.SelectionStart = 0;
            this.txtphone.ShortcutsEnabled = true;
            this.txtphone.Size = new System.Drawing.Size(223, 37);
            this.txtphone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtphone.TabIndex = 66;
            this.txtphone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtphone.TextMarginBottom = 0;
            this.txtphone.TextMarginLeft = 3;
            this.txtphone.TextMarginTop = 0;
            this.txtphone.TextPlaceholder = "";
            this.txtphone.UseSystemPasswordChar = false;
            this.txtphone.WordWrap = true;
            // 
            // Form_StaffDetails
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(42)))), ((int)(((byte)(45)))));
            this.ClientSize = new System.Drawing.Size(792, 450);
            this.Controls.Add(this.labelState);
            this.Controls.Add(this.txtpoisition);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.txtstaffid);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.btnsave);
            this.Controls.Add(this.labelCustomerID);
            this.Controls.Add(this.panelTopBar);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form_StaffDetails";
            this.Text = "Form_StaffDetails";
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuGroupBox1.ResumeLayout(false);
            this.panelTopBar.ResumeLayout(false);
            this.panelTopBar.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private System.Windows.Forms.Label labelStreet;
        private System.Windows.Forms.Label labelCity;
        private Bunifu.UI.WinForms.BunifuTextBox txtaddress;
        private Bunifu.UI.WinForms.BunifuTextBox txtemail;
        private Bunifu.UI.WinForms.BunifuTextBox txtstaffid;
        private Bunifu.UI.WinForms.BunifuTextBox txtpass;
        private Bunifu.UI.WinForms.BunifuTextBox txtusername;
        private Bunifu.UI.WinForms.BunifuTextBox txtsalary;
        private Bunifu.UI.WinForms.BunifuTextBox txtbirthday;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private System.Windows.Forms.Label labelFName;
        private System.Windows.Forms.Label labelEmail;
        private System.Windows.Forms.Label labelPhone;
        private System.Windows.Forms.Label labelLName;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnsave;
        private System.Windows.Forms.Label labelCustomerID;
        private System.Windows.Forms.Panel panelTopBar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.Button btn_Quit;
        private System.Windows.Forms.Label labelState;
        private Bunifu.UI.WinForms.BunifuTextBox txtpoisition;
        private Bunifu.UI.WinForms.BunifuTextBox txtphone;
        private System.Windows.Forms.Label label1;
    }
}