
namespace Gear_Store
{
    partial class Form_Brand
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle8 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form_Brand));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle10 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle11 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle12 = new System.Windows.Forms.DataGridViewCellStyle();
            this.dgvBrand = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.label3 = new System.Windows.Forms.Label();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.btn_Quit = new System.Windows.Forms.Button();
            this.txtBrandName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnDelBrand = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAddBrand = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtCategoryName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnDelPCatg = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAddlPCatg = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dgvcatg = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.label1 = new System.Windows.Forms.Label();
            this.errorProvider = new System.Windows.Forms.ErrorProvider(this.components);
            this.Message = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.dgvBrand)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvcatg)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider)).BeginInit();
            this.SuspendLayout();
            // 
            // dgvBrand
            // 
            this.dgvBrand.AllowCustomTheming = false;
            this.dgvBrand.AllowUserToAddRows = false;
            this.dgvBrand.AllowUserToDeleteRows = false;
            dataGridViewCellStyle7.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle7.ForeColor = System.Drawing.Color.Black;
            this.dgvBrand.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle7;
            this.dgvBrand.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvBrand.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvBrand.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvBrand.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle8.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle8.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle8.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle8.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle8.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle8.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle8.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvBrand.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle8;
            this.dgvBrand.ColumnHeadersHeight = 40;
            this.dgvBrand.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvBrand.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvBrand.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvBrand.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvBrand.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvBrand.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvBrand.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvBrand.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvBrand.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvBrand.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvBrand.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvBrand.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvBrand.CurrentTheme.Name = null;
            this.dgvBrand.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvBrand.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvBrand.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvBrand.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvBrand.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle9.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle9.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle9.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle9.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle9.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle9.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle9.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvBrand.DefaultCellStyle = dataGridViewCellStyle9;
            this.dgvBrand.EnableHeadersVisualStyles = false;
            this.dgvBrand.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvBrand.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvBrand.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvBrand.HeaderForeColor = System.Drawing.Color.White;
            this.dgvBrand.Location = new System.Drawing.Point(29, 111);
            this.dgvBrand.Margin = new System.Windows.Forms.Padding(2);
            this.dgvBrand.Name = "dgvBrand";
            this.dgvBrand.ReadOnly = true;
            this.dgvBrand.RowHeadersVisible = false;
            this.dgvBrand.RowTemplate.Height = 40;
            this.dgvBrand.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvBrand.Size = new System.Drawing.Size(344, 288);
            this.dgvBrand.TabIndex = 0;
            this.dgvBrand.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgvBrand.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvBrand_CellClick);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(26, 37);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(104, 21);
            this.label3.TabIndex = 73;
            this.label3.Text = "Brand Name:";
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // btn_Quit
            // 
            this.btn_Quit.BackColor = System.Drawing.Color.Transparent;
            this.btn_Quit.FlatAppearance.BorderSize = 0;
            this.btn_Quit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn_Quit.Image = ((System.Drawing.Image)(resources.GetObject("btn_Quit.Image")));
            this.btn_Quit.Location = new System.Drawing.Point(736, 3);
            this.btn_Quit.Name = "btn_Quit";
            this.btn_Quit.Size = new System.Drawing.Size(42, 41);
            this.btn_Quit.TabIndex = 75;
            this.btn_Quit.UseVisualStyleBackColor = false;
            this.btn_Quit.Click += new System.EventHandler(this.btn_Quit_Click);
            // 
            // txtBrandName
            // 
            this.txtBrandName.AcceptsReturn = false;
            this.txtBrandName.AcceptsTab = false;
            this.txtBrandName.AnimationSpeed = 200;
            this.txtBrandName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBrandName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBrandName.BackColor = System.Drawing.Color.Transparent;
            this.txtBrandName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBrandName.BackgroundImage")));
            this.txtBrandName.BorderColorActive = System.Drawing.Color.Orange;
            this.txtBrandName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBrandName.BorderColorHover = System.Drawing.Color.Orange;
            this.txtBrandName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtBrandName.BorderRadius = 1;
            this.txtBrandName.BorderThickness = 1;
            this.txtBrandName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBrandName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBrandName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtBrandName.DefaultText = "";
            this.txtBrandName.FillColor = System.Drawing.Color.White;
            this.txtBrandName.ForeColor = System.Drawing.Color.Black;
            this.txtBrandName.HideSelection = true;
            this.txtBrandName.IconLeft = null;
            this.txtBrandName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBrandName.IconPadding = 10;
            this.txtBrandName.IconRight = null;
            this.txtBrandName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBrandName.Lines = new string[0];
            this.txtBrandName.Location = new System.Drawing.Point(29, 58);
            this.txtBrandName.MaxLength = 32767;
            this.txtBrandName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBrandName.Modified = false;
            this.txtBrandName.Multiline = false;
            this.txtBrandName.Name = "txtBrandName";
            stateProperties13.BorderColor = System.Drawing.Color.Orange;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBrandName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBrandName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Orange;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBrandName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBrandName.OnIdleState = stateProperties16;
            this.txtBrandName.Padding = new System.Windows.Forms.Padding(3);
            this.txtBrandName.PasswordChar = '\0';
            this.txtBrandName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBrandName.PlaceholderText = "";
            this.txtBrandName.ReadOnly = false;
            this.txtBrandName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBrandName.SelectedText = "";
            this.txtBrandName.SelectionLength = 0;
            this.txtBrandName.SelectionStart = 0;
            this.txtBrandName.ShortcutsEnabled = true;
            this.txtBrandName.Size = new System.Drawing.Size(227, 32);
            this.txtBrandName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBrandName.TabIndex = 74;
            this.txtBrandName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBrandName.TextMarginBottom = 0;
            this.txtBrandName.TextMarginLeft = 3;
            this.txtBrandName.TextMarginTop = 0;
            this.txtBrandName.TextPlaceholder = "";
            this.txtBrandName.UseSystemPasswordChar = false;
            this.txtBrandName.WordWrap = true;
            // 
            // btnDelBrand
            // 
            this.btnDelBrand.AllowAnimations = true;
            this.btnDelBrand.AllowMouseEffects = true;
            this.btnDelBrand.AllowToggling = false;
            this.btnDelBrand.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnDelBrand.AnimationSpeed = 200;
            this.btnDelBrand.AutoGenerateColors = false;
            this.btnDelBrand.AutoRoundBorders = false;
            this.btnDelBrand.AutoSizeLeftIcon = true;
            this.btnDelBrand.AutoSizeRightIcon = true;
            this.btnDelBrand.BackColor = System.Drawing.Color.Transparent;
            this.btnDelBrand.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelBrand.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelBrand.BackgroundImage")));
            this.btnDelBrand.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelBrand.ButtonText = "";
            this.btnDelBrand.ButtonTextMarginLeft = 0;
            this.btnDelBrand.ColorContrastOnClick = 45;
            this.btnDelBrand.ColorContrastOnHover = 45;
            this.btnDelBrand.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnDelBrand.CustomizableEdges = borderEdges7;
            this.btnDelBrand.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelBrand.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelBrand.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelBrand.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelBrand.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnDelBrand.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDelBrand.ForeColor = System.Drawing.Color.White;
            this.btnDelBrand.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDelBrand.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelBrand.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDelBrand.IconMarginLeft = 11;
            this.btnDelBrand.IconPadding = 10;
            this.btnDelBrand.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDelBrand.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelBrand.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDelBrand.IconSize = 25;
            this.btnDelBrand.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelBrand.IdleBorderRadius = 1;
            this.btnDelBrand.IdleBorderThickness = 1;
            this.btnDelBrand.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelBrand.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDelBrand.IdleIconLeftImage")));
            this.btnDelBrand.IdleIconRightImage = null;
            this.btnDelBrand.IndicateFocus = false;
            this.btnDelBrand.Location = new System.Drawing.Point(328, 58);
            this.btnDelBrand.Name = "btnDelBrand";
            this.btnDelBrand.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelBrand.OnDisabledState.BorderRadius = 1;
            this.btnDelBrand.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelBrand.OnDisabledState.BorderThickness = 1;
            this.btnDelBrand.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelBrand.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelBrand.OnDisabledState.IconLeftImage = null;
            this.btnDelBrand.OnDisabledState.IconRightImage = null;
            this.btnDelBrand.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelBrand.onHoverState.BorderRadius = 1;
            this.btnDelBrand.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelBrand.onHoverState.BorderThickness = 1;
            this.btnDelBrand.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelBrand.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.btnDelBrand.onHoverState.IconLeftImage = null;
            this.btnDelBrand.onHoverState.IconRightImage = null;
            this.btnDelBrand.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelBrand.OnIdleState.BorderRadius = 1;
            this.btnDelBrand.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelBrand.OnIdleState.BorderThickness = 1;
            this.btnDelBrand.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelBrand.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDelBrand.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDelBrand.OnIdleState.IconLeftImage")));
            this.btnDelBrand.OnIdleState.IconRightImage = null;
            this.btnDelBrand.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelBrand.OnPressedState.BorderRadius = 1;
            this.btnDelBrand.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelBrand.OnPressedState.BorderThickness = 1;
            this.btnDelBrand.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelBrand.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.btnDelBrand.OnPressedState.IconLeftImage = null;
            this.btnDelBrand.OnPressedState.IconRightImage = null;
            this.btnDelBrand.Size = new System.Drawing.Size(44, 39);
            this.btnDelBrand.TabIndex = 18;
            this.btnDelBrand.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelBrand.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDelBrand.TextMarginLeft = 0;
            this.btnDelBrand.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDelBrand.UseDefaultRadiusAndThickness = true;
            this.btnDelBrand.Click += new System.EventHandler(this.btnDelBrand_Click);
            // 
            // btnAddBrand
            // 
            this.btnAddBrand.AllowAnimations = true;
            this.btnAddBrand.AllowMouseEffects = true;
            this.btnAddBrand.AllowToggling = false;
            this.btnAddBrand.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAddBrand.AnimationSpeed = 200;
            this.btnAddBrand.AutoGenerateColors = false;
            this.btnAddBrand.AutoRoundBorders = false;
            this.btnAddBrand.AutoSizeLeftIcon = true;
            this.btnAddBrand.AutoSizeRightIcon = true;
            this.btnAddBrand.BackColor = System.Drawing.Color.Transparent;
            this.btnAddBrand.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddBrand.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddBrand.BackgroundImage")));
            this.btnAddBrand.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddBrand.ButtonText = "";
            this.btnAddBrand.ButtonTextMarginLeft = 0;
            this.btnAddBrand.ColorContrastOnClick = 45;
            this.btnAddBrand.ColorContrastOnHover = 45;
            this.btnAddBrand.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnAddBrand.CustomizableEdges = borderEdges8;
            this.btnAddBrand.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddBrand.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddBrand.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddBrand.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddBrand.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnAddBrand.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddBrand.ForeColor = System.Drawing.Color.White;
            this.btnAddBrand.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddBrand.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddBrand.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddBrand.IconMarginLeft = 11;
            this.btnAddBrand.IconPadding = 10;
            this.btnAddBrand.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddBrand.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddBrand.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddBrand.IconSize = 25;
            this.btnAddBrand.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddBrand.IdleBorderRadius = 1;
            this.btnAddBrand.IdleBorderThickness = 1;
            this.btnAddBrand.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddBrand.IdleIconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.btnAddBrand.IdleIconRightImage = null;
            this.btnAddBrand.IndicateFocus = false;
            this.btnAddBrand.Location = new System.Drawing.Point(278, 58);
            this.btnAddBrand.Name = "btnAddBrand";
            this.btnAddBrand.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddBrand.OnDisabledState.BorderRadius = 1;
            this.btnAddBrand.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddBrand.OnDisabledState.BorderThickness = 1;
            this.btnAddBrand.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddBrand.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddBrand.OnDisabledState.IconLeftImage = null;
            this.btnAddBrand.OnDisabledState.IconRightImage = null;
            this.btnAddBrand.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddBrand.onHoverState.BorderRadius = 1;
            this.btnAddBrand.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddBrand.onHoverState.BorderThickness = 1;
            this.btnAddBrand.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddBrand.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.btnAddBrand.onHoverState.IconLeftImage = null;
            this.btnAddBrand.onHoverState.IconRightImage = null;
            this.btnAddBrand.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddBrand.OnIdleState.BorderRadius = 1;
            this.btnAddBrand.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddBrand.OnIdleState.BorderThickness = 1;
            this.btnAddBrand.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddBrand.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddBrand.OnIdleState.IconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.btnAddBrand.OnIdleState.IconRightImage = null;
            this.btnAddBrand.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddBrand.OnPressedState.BorderRadius = 1;
            this.btnAddBrand.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddBrand.OnPressedState.BorderThickness = 1;
            this.btnAddBrand.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddBrand.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.btnAddBrand.OnPressedState.IconLeftImage = null;
            this.btnAddBrand.OnPressedState.IconRightImage = null;
            this.btnAddBrand.Size = new System.Drawing.Size(44, 39);
            this.btnAddBrand.TabIndex = 17;
            this.btnAddBrand.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddBrand.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddBrand.TextMarginLeft = 0;
            this.btnAddBrand.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddBrand.UseDefaultRadiusAndThickness = true;
            this.btnAddBrand.Click += new System.EventHandler(this.btnAddBrand_Click);
            // 
            // txtCategoryName
            // 
            this.txtCategoryName.AcceptsReturn = false;
            this.txtCategoryName.AcceptsTab = false;
            this.txtCategoryName.AnimationSpeed = 200;
            this.txtCategoryName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCategoryName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCategoryName.BackColor = System.Drawing.Color.Transparent;
            this.txtCategoryName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCategoryName.BackgroundImage")));
            this.txtCategoryName.BorderColorActive = System.Drawing.Color.Orange;
            this.txtCategoryName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCategoryName.BorderColorHover = System.Drawing.Color.Orange;
            this.txtCategoryName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCategoryName.BorderRadius = 1;
            this.txtCategoryName.BorderThickness = 1;
            this.txtCategoryName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCategoryName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategoryName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCategoryName.DefaultText = "";
            this.txtCategoryName.FillColor = System.Drawing.Color.White;
            this.txtCategoryName.ForeColor = System.Drawing.Color.Black;
            this.txtCategoryName.HideSelection = true;
            this.txtCategoryName.IconLeft = null;
            this.txtCategoryName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategoryName.IconPadding = 10;
            this.txtCategoryName.IconRight = null;
            this.txtCategoryName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategoryName.Lines = new string[0];
            this.txtCategoryName.Location = new System.Drawing.Point(416, 58);
            this.txtCategoryName.MaxLength = 32767;
            this.txtCategoryName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCategoryName.Modified = false;
            this.txtCategoryName.Multiline = false;
            this.txtCategoryName.Name = "txtCategoryName";
            stateProperties9.BorderColor = System.Drawing.Color.Orange;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategoryName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCategoryName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Orange;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategoryName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategoryName.OnIdleState = stateProperties12;
            this.txtCategoryName.Padding = new System.Windows.Forms.Padding(3);
            this.txtCategoryName.PasswordChar = '\0';
            this.txtCategoryName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCategoryName.PlaceholderText = "";
            this.txtCategoryName.ReadOnly = false;
            this.txtCategoryName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCategoryName.SelectedText = "";
            this.txtCategoryName.SelectionLength = 0;
            this.txtCategoryName.SelectionStart = 0;
            this.txtCategoryName.ShortcutsEnabled = true;
            this.txtCategoryName.Size = new System.Drawing.Size(227, 32);
            this.txtCategoryName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCategoryName.TabIndex = 79;
            this.txtCategoryName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCategoryName.TextMarginBottom = 0;
            this.txtCategoryName.TextMarginLeft = 3;
            this.txtCategoryName.TextMarginTop = 0;
            this.txtCategoryName.TextPlaceholder = "";
            this.txtCategoryName.UseSystemPasswordChar = false;
            this.txtCategoryName.WordWrap = true;
            // 
            // btnDelPCatg
            // 
            this.btnDelPCatg.AllowAnimations = true;
            this.btnDelPCatg.AllowMouseEffects = true;
            this.btnDelPCatg.AllowToggling = false;
            this.btnDelPCatg.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnDelPCatg.AnimationSpeed = 200;
            this.btnDelPCatg.AutoGenerateColors = false;
            this.btnDelPCatg.AutoRoundBorders = false;
            this.btnDelPCatg.AutoSizeLeftIcon = true;
            this.btnDelPCatg.AutoSizeRightIcon = true;
            this.btnDelPCatg.BackColor = System.Drawing.Color.Transparent;
            this.btnDelPCatg.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelPCatg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelPCatg.BackgroundImage")));
            this.btnDelPCatg.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelPCatg.ButtonText = "";
            this.btnDelPCatg.ButtonTextMarginLeft = 0;
            this.btnDelPCatg.ColorContrastOnClick = 45;
            this.btnDelPCatg.ColorContrastOnHover = 45;
            this.btnDelPCatg.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnDelPCatg.CustomizableEdges = borderEdges5;
            this.btnDelPCatg.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelPCatg.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelPCatg.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelPCatg.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelPCatg.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnDelPCatg.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDelPCatg.ForeColor = System.Drawing.Color.White;
            this.btnDelPCatg.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDelPCatg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelPCatg.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDelPCatg.IconMarginLeft = 11;
            this.btnDelPCatg.IconPadding = 10;
            this.btnDelPCatg.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDelPCatg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelPCatg.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDelPCatg.IconSize = 25;
            this.btnDelPCatg.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelPCatg.IdleBorderRadius = 1;
            this.btnDelPCatg.IdleBorderThickness = 1;
            this.btnDelPCatg.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelPCatg.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDelPCatg.IdleIconLeftImage")));
            this.btnDelPCatg.IdleIconRightImage = null;
            this.btnDelPCatg.IndicateFocus = false;
            this.btnDelPCatg.Location = new System.Drawing.Point(715, 58);
            this.btnDelPCatg.Name = "btnDelPCatg";
            this.btnDelPCatg.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelPCatg.OnDisabledState.BorderRadius = 1;
            this.btnDelPCatg.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelPCatg.OnDisabledState.BorderThickness = 1;
            this.btnDelPCatg.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelPCatg.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelPCatg.OnDisabledState.IconLeftImage = null;
            this.btnDelPCatg.OnDisabledState.IconRightImage = null;
            this.btnDelPCatg.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelPCatg.onHoverState.BorderRadius = 1;
            this.btnDelPCatg.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelPCatg.onHoverState.BorderThickness = 1;
            this.btnDelPCatg.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelPCatg.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.btnDelPCatg.onHoverState.IconLeftImage = null;
            this.btnDelPCatg.onHoverState.IconRightImage = null;
            this.btnDelPCatg.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelPCatg.OnIdleState.BorderRadius = 1;
            this.btnDelPCatg.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelPCatg.OnIdleState.BorderThickness = 1;
            this.btnDelPCatg.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnDelPCatg.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDelPCatg.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDelPCatg.OnIdleState.IconLeftImage")));
            this.btnDelPCatg.OnIdleState.IconRightImage = null;
            this.btnDelPCatg.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelPCatg.OnPressedState.BorderRadius = 1;
            this.btnDelPCatg.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelPCatg.OnPressedState.BorderThickness = 1;
            this.btnDelPCatg.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnDelPCatg.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.btnDelPCatg.OnPressedState.IconLeftImage = null;
            this.btnDelPCatg.OnPressedState.IconRightImage = null;
            this.btnDelPCatg.Size = new System.Drawing.Size(44, 39);
            this.btnDelPCatg.TabIndex = 78;
            this.btnDelPCatg.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelPCatg.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDelPCatg.TextMarginLeft = 0;
            this.btnDelPCatg.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDelPCatg.UseDefaultRadiusAndThickness = true;
            this.btnDelPCatg.Click += new System.EventHandler(this.btnDelPCatg_Click);
            // 
            // btnAddlPCatg
            // 
            this.btnAddlPCatg.AllowAnimations = true;
            this.btnAddlPCatg.AllowMouseEffects = true;
            this.btnAddlPCatg.AllowToggling = false;
            this.btnAddlPCatg.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAddlPCatg.AnimationSpeed = 200;
            this.btnAddlPCatg.AutoGenerateColors = false;
            this.btnAddlPCatg.AutoRoundBorders = false;
            this.btnAddlPCatg.AutoSizeLeftIcon = true;
            this.btnAddlPCatg.AutoSizeRightIcon = true;
            this.btnAddlPCatg.BackColor = System.Drawing.Color.Transparent;
            this.btnAddlPCatg.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddlPCatg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddlPCatg.BackgroundImage")));
            this.btnAddlPCatg.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddlPCatg.ButtonText = "";
            this.btnAddlPCatg.ButtonTextMarginLeft = 0;
            this.btnAddlPCatg.ColorContrastOnClick = 45;
            this.btnAddlPCatg.ColorContrastOnHover = 45;
            this.btnAddlPCatg.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnAddlPCatg.CustomizableEdges = borderEdges6;
            this.btnAddlPCatg.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddlPCatg.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddlPCatg.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddlPCatg.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddlPCatg.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnAddlPCatg.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddlPCatg.ForeColor = System.Drawing.Color.White;
            this.btnAddlPCatg.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddlPCatg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddlPCatg.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddlPCatg.IconMarginLeft = 11;
            this.btnAddlPCatg.IconPadding = 10;
            this.btnAddlPCatg.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddlPCatg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddlPCatg.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddlPCatg.IconSize = 25;
            this.btnAddlPCatg.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddlPCatg.IdleBorderRadius = 1;
            this.btnAddlPCatg.IdleBorderThickness = 1;
            this.btnAddlPCatg.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddlPCatg.IdleIconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.btnAddlPCatg.IdleIconRightImage = null;
            this.btnAddlPCatg.IndicateFocus = false;
            this.btnAddlPCatg.Location = new System.Drawing.Point(664, 58);
            this.btnAddlPCatg.Name = "btnAddlPCatg";
            this.btnAddlPCatg.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddlPCatg.OnDisabledState.BorderRadius = 1;
            this.btnAddlPCatg.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddlPCatg.OnDisabledState.BorderThickness = 1;
            this.btnAddlPCatg.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddlPCatg.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddlPCatg.OnDisabledState.IconLeftImage = null;
            this.btnAddlPCatg.OnDisabledState.IconRightImage = null;
            this.btnAddlPCatg.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddlPCatg.onHoverState.BorderRadius = 1;
            this.btnAddlPCatg.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddlPCatg.onHoverState.BorderThickness = 1;
            this.btnAddlPCatg.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddlPCatg.onHoverState.ForeColor = System.Drawing.Color.Orange;
            this.btnAddlPCatg.onHoverState.IconLeftImage = null;
            this.btnAddlPCatg.onHoverState.IconRightImage = null;
            this.btnAddlPCatg.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddlPCatg.OnIdleState.BorderRadius = 1;
            this.btnAddlPCatg.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddlPCatg.OnIdleState.BorderThickness = 1;
            this.btnAddlPCatg.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnAddlPCatg.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddlPCatg.OnIdleState.IconLeftImage = global::Gear_Store.Properties.Resources.plus_math_48px;
            this.btnAddlPCatg.OnIdleState.IconRightImage = null;
            this.btnAddlPCatg.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddlPCatg.OnPressedState.BorderRadius = 1;
            this.btnAddlPCatg.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddlPCatg.OnPressedState.BorderThickness = 1;
            this.btnAddlPCatg.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnAddlPCatg.OnPressedState.ForeColor = System.Drawing.Color.Orange;
            this.btnAddlPCatg.OnPressedState.IconLeftImage = null;
            this.btnAddlPCatg.OnPressedState.IconRightImage = null;
            this.btnAddlPCatg.Size = new System.Drawing.Size(44, 39);
            this.btnAddlPCatg.TabIndex = 77;
            this.btnAddlPCatg.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddlPCatg.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddlPCatg.TextMarginLeft = 0;
            this.btnAddlPCatg.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddlPCatg.UseDefaultRadiusAndThickness = true;
            this.btnAddlPCatg.Click += new System.EventHandler(this.btnAddlPCatg_Click);
            // 
            // dgvcatg
            // 
            this.dgvcatg.AllowCustomTheming = false;
            this.dgvcatg.AllowUserToAddRows = false;
            this.dgvcatg.AllowUserToDeleteRows = false;
            dataGridViewCellStyle10.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle10.ForeColor = System.Drawing.Color.Black;
            this.dgvcatg.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle10;
            this.dgvcatg.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvcatg.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvcatg.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvcatg.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle11.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle11.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle11.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle11.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle11.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle11.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle11.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvcatg.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle11;
            this.dgvcatg.ColumnHeadersHeight = 40;
            this.dgvcatg.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvcatg.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvcatg.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvcatg.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvcatg.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvcatg.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvcatg.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvcatg.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvcatg.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvcatg.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvcatg.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvcatg.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvcatg.CurrentTheme.Name = null;
            this.dgvcatg.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvcatg.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvcatg.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvcatg.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvcatg.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle12.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle12.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle12.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle12.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle12.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle12.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle12.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvcatg.DefaultCellStyle = dataGridViewCellStyle12;
            this.dgvcatg.EnableHeadersVisualStyles = false;
            this.dgvcatg.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvcatg.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvcatg.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvcatg.HeaderForeColor = System.Drawing.Color.White;
            this.dgvcatg.Location = new System.Drawing.Point(416, 111);
            this.dgvcatg.Margin = new System.Windows.Forms.Padding(2);
            this.dgvcatg.Name = "dgvcatg";
            this.dgvcatg.ReadOnly = true;
            this.dgvcatg.RowHeadersVisible = false;
            this.dgvcatg.RowTemplate.Height = 40;
            this.dgvcatg.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvcatg.Size = new System.Drawing.Size(344, 288);
            this.dgvcatg.TabIndex = 76;
            this.dgvcatg.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgvcatg.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dvgcatg_CellClick);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(412, 37);
            this.label1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(144, 21);
            this.label1.TabIndex = 80;
            this.label1.Text = "Product Category:";
            // 
            // errorProvider
            // 
            this.errorProvider.ContainerControl = this;
            // 
            // Message
            // 
            this.Message.AllowDragging = false;
            this.Message.AllowMultipleViews = true;
            this.Message.ClickToClose = true;
            this.Message.DoubleClickToClose = true;
            this.Message.DurationAfterIdle = 3000;
            this.Message.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Message.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Message.ErrorOptions.ActionBorderRadius = 1;
            this.Message.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Message.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Message.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.Message.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.Message.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.Message.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Message.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.Message.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.Message.ErrorOptions.IconLeftMargin = 12;
            this.Message.FadeCloseIcon = false;
            this.Message.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.Message.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Message.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Message.InformationOptions.ActionBorderRadius = 1;
            this.Message.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Message.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Message.InformationOptions.BackColor = System.Drawing.Color.White;
            this.Message.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.Message.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.Message.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Message.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.Message.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.Message.InformationOptions.IconLeftMargin = 12;
            this.Message.Margin = 10;
            this.Message.MaximumSize = new System.Drawing.Size(0, 0);
            this.Message.MaximumViews = 7;
            this.Message.MessageRightMargin = 15;
            this.Message.MinimumSize = new System.Drawing.Size(0, 0);
            this.Message.ShowBorders = false;
            this.Message.ShowCloseIcon = false;
            this.Message.ShowIcon = true;
            this.Message.ShowShadows = true;
            this.Message.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Message.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Message.SuccessOptions.ActionBorderRadius = 1;
            this.Message.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Message.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Message.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.Message.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.Message.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.Message.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Message.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.Message.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.Message.SuccessOptions.IconLeftMargin = 12;
            this.Message.ViewsMargin = 7;
            this.Message.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Message.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Message.WarningOptions.ActionBorderRadius = 1;
            this.Message.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Message.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Message.WarningOptions.BackColor = System.Drawing.Color.White;
            this.Message.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.Message.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.Message.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Message.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.Message.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.Message.WarningOptions.IconLeftMargin = 12;
            this.Message.ZoomCloseIcon = true;
            // 
            // Form_Brand
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(42)))), ((int)(((byte)(45)))));
            this.ClientSize = new System.Drawing.Size(788, 431);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.txtCategoryName);
            this.Controls.Add(this.btnDelPCatg);
            this.Controls.Add(this.btnAddlPCatg);
            this.Controls.Add(this.dgvcatg);
            this.Controls.Add(this.btn_Quit);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.txtBrandName);
            this.Controls.Add(this.btnDelBrand);
            this.Controls.Add(this.btnAddBrand);
            this.Controls.Add(this.dgvBrand);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "Form_Brand";
            this.Text = "Form_Brand";
            this.Load += new System.EventHandler(this.Form_Brand_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvBrand)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvcatg)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView dgvBrand;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelBrand;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddBrand;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox txtBrandName;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private System.Windows.Forms.Button btn_Quit;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtCategoryName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelPCatg;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddlPCatg;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvcatg;
        private System.Windows.Forms.ErrorProvider errorProvider;
        private Bunifu.UI.WinForms.BunifuSnackbar Message;
    }
}