
namespace Gear_Store
{
    partial class Form_CustomerDetails
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form_CustomerDetails));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panelTopBar = new System.Windows.Forms.Panel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.labelCustomerID = new System.Windows.Forms.Label();
            this.labelFName = new System.Windows.Forms.Label();
            this.labelLName = new System.Windows.Forms.Label();
            this.labelPhone = new System.Windows.Forms.Label();
            this.labelEmail = new System.Windows.Forms.Label();
            this.labelStreet = new System.Windows.Forms.Label();
            this.labelCity = new System.Windows.Forms.Label();
            this.labelState = new System.Windows.Forms.Label();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtState = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtStreet = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtLName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtFName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnsave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtCustomerID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btn_Quit = new System.Windows.Forms.Button();
            this.panelTopBar.SuspendLayout();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // panelTopBar
            // 
            this.panelTopBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.panelTopBar.Controls.Add(this.bunifuLabel2);
            this.panelTopBar.Controls.Add(this.bunifuLabel1);
            this.panelTopBar.Controls.Add(this.bunifuPictureBox1);
            this.panelTopBar.Controls.Add(this.btn_Quit);
            this.panelTopBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTopBar.ForeColor = System.Drawing.Color.Black;
            this.panelTopBar.Location = new System.Drawing.Point(0, 0);
            this.panelTopBar.Name = "panelTopBar";
            this.panelTopBar.Size = new System.Drawing.Size(808, 35);
            this.panelTopBar.TabIndex = 2;
            this.panelTopBar.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panelTopBar_MouseDown);
            this.panelTopBar.MouseMove += new System.Windows.Forms.MouseEventHandler(this.panelTopBar_MouseMove);
            this.panelTopBar.MouseUp += new System.Windows.Forms.MouseEventHandler(this.panelTopBar_MouseUp);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(371, 8);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(39, 17);
            this.bunifuLabel2.TabIndex = 4;
            this.bunifuLabel2.Text = "Mode";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Orange;
            this.bunifuLabel1.Location = new System.Drawing.Point(61, 8);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(100, 17);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "Customer Info";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // labelCustomerID
            // 
            this.labelCustomerID.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelCustomerID.ForeColor = System.Drawing.Color.White;
            this.labelCustomerID.Location = new System.Drawing.Point(45, 79);
            this.labelCustomerID.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelCustomerID.Name = "labelCustomerID";
            this.labelCustomerID.Size = new System.Drawing.Size(106, 37);
            this.labelCustomerID.TabIndex = 38;
            this.labelCustomerID.Text = "Customer ID:";
            this.labelCustomerID.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.labelCustomerID.Click += new System.EventHandler(this.txtColorChange_Click);
            // 
            // labelFName
            // 
            this.labelFName.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelFName.ForeColor = System.Drawing.Color.White;
            this.labelFName.Location = new System.Drawing.Point(24, 28);
            this.labelFName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelFName.Name = "labelFName";
            this.labelFName.Size = new System.Drawing.Size(95, 37);
            this.labelFName.TabIndex = 40;
            this.labelFName.Text = "First Name:";
            this.labelFName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelLName
            // 
            this.labelLName.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelLName.ForeColor = System.Drawing.Color.White;
            this.labelLName.Location = new System.Drawing.Point(24, 79);
            this.labelLName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelLName.Name = "labelLName";
            this.labelLName.Size = new System.Drawing.Size(95, 37);
            this.labelLName.TabIndex = 41;
            this.labelLName.Text = "Last Name:";
            this.labelLName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelPhone
            // 
            this.labelPhone.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelPhone.ForeColor = System.Drawing.Color.White;
            this.labelPhone.Location = new System.Drawing.Point(24, 130);
            this.labelPhone.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelPhone.Name = "labelPhone";
            this.labelPhone.Size = new System.Drawing.Size(69, 36);
            this.labelPhone.TabIndex = 42;
            this.labelPhone.Text = "Phone:";
            this.labelPhone.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelEmail
            // 
            this.labelEmail.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelEmail.ForeColor = System.Drawing.Color.White;
            this.labelEmail.Location = new System.Drawing.Point(24, 180);
            this.labelEmail.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelEmail.Name = "labelEmail";
            this.labelEmail.Size = new System.Drawing.Size(59, 37);
            this.labelEmail.TabIndex = 43;
            this.labelEmail.Text = "Email:";
            this.labelEmail.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelStreet
            // 
            this.labelStreet.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelStreet.ForeColor = System.Drawing.Color.White;
            this.labelStreet.Location = new System.Drawing.Point(29, 47);
            this.labelStreet.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelStreet.Name = "labelStreet";
            this.labelStreet.Size = new System.Drawing.Size(69, 37);
            this.labelStreet.TabIndex = 44;
            this.labelStreet.Text = "Street:";
            this.labelStreet.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelCity
            // 
            this.labelCity.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelCity.ForeColor = System.Drawing.Color.White;
            this.labelCity.Location = new System.Drawing.Point(29, 100);
            this.labelCity.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelCity.Name = "labelCity";
            this.labelCity.Size = new System.Drawing.Size(55, 37);
            this.labelCity.TabIndex = 45;
            this.labelCity.Text = "City:";
            this.labelCity.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelState
            // 
            this.labelState.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelState.ForeColor = System.Drawing.Color.White;
            this.labelState.Location = new System.Drawing.Point(29, 153);
            this.labelState.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelState.Name = "labelState";
            this.labelState.Size = new System.Drawing.Size(69, 37);
            this.labelState.TabIndex = 46;
            this.labelState.Text = "State:";
            this.labelState.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.labelFName);
            this.bunifuGroupBox1.Controls.Add(this.labelEmail);
            this.bunifuGroupBox1.Controls.Add(this.labelPhone);
            this.bunifuGroupBox1.Controls.Add(this.labelLName);
            this.bunifuGroupBox1.Controls.Add(this.txtLName);
            this.bunifuGroupBox1.Controls.Add(this.txtFName);
            this.bunifuGroupBox1.Controls.Add(this.txtEmail);
            this.bunifuGroupBox1.Controls.Add(this.txtPhone);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.Orange;
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(21, 144);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(389, 238);
            this.bunifuGroupBox1.TabIndex = 68;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Basic Info";
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.labelStreet);
            this.bunifuGroupBox2.Controls.Add(this.labelState);
            this.bunifuGroupBox2.Controls.Add(this.txtState);
            this.bunifuGroupBox2.Controls.Add(this.labelCity);
            this.bunifuGroupBox2.Controls.Add(this.txtCity);
            this.bunifuGroupBox2.Controls.Add(this.txtStreet);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold);
            this.bunifuGroupBox2.ForeColor = System.Drawing.Color.Orange;
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(422, 144);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(366, 238);
            this.bunifuGroupBox2.TabIndex = 69;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Address";
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Cancel";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges1;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnCancel.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.IdleBorderRadius = 15;
            this.btnCancel.IdleBorderThickness = 1;
            this.btnCancel.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(670, 421);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 15;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.onHoverState.BorderRadius = 15;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.OnIdleState.BorderRadius = 15;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.OnPressedState.BorderRadius = 15;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(118, 44);
            this.btnCancel.TabIndex = 70;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // txtState
            // 
            this.txtState.AcceptsReturn = false;
            this.txtState.AcceptsTab = false;
            this.txtState.AnimationSpeed = 200;
            this.txtState.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtState.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtState.BackColor = System.Drawing.Color.Transparent;
            this.txtState.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtState.BackgroundImage")));
            this.txtState.BorderColorActive = System.Drawing.Color.Orange;
            this.txtState.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtState.BorderColorHover = System.Drawing.Color.Orange;
            this.txtState.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtState.BorderRadius = 1;
            this.txtState.BorderThickness = 1;
            this.txtState.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtState.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtState.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtState.DefaultText = "";
            this.txtState.FillColor = System.Drawing.Color.White;
            this.txtState.ForeColor = System.Drawing.Color.Black;
            this.txtState.HideSelection = true;
            this.txtState.IconLeft = null;
            this.txtState.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtState.IconPadding = 10;
            this.txtState.IconRight = null;
            this.txtState.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtState.Lines = new string[0];
            this.txtState.Location = new System.Drawing.Point(105, 158);
            this.txtState.MaxLength = 32767;
            this.txtState.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtState.Modified = false;
            this.txtState.Multiline = false;
            this.txtState.Name = "txtState";
            stateProperties1.BorderColor = System.Drawing.Color.Orange;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtState.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtState.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Orange;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtState.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtState.OnIdleState = stateProperties4;
            this.txtState.Padding = new System.Windows.Forms.Padding(3);
            this.txtState.PasswordChar = '\0';
            this.txtState.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtState.PlaceholderText = "";
            this.txtState.ReadOnly = false;
            this.txtState.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtState.SelectedText = "";
            this.txtState.SelectionLength = 0;
            this.txtState.SelectionStart = 0;
            this.txtState.ShortcutsEnabled = true;
            this.txtState.Size = new System.Drawing.Size(223, 37);
            this.txtState.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtState.TabIndex = 65;
            this.txtState.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtState.TextMarginBottom = 0;
            this.txtState.TextMarginLeft = 3;
            this.txtState.TextMarginTop = 0;
            this.txtState.TextPlaceholder = "";
            this.txtState.UseSystemPasswordChar = false;
            this.txtState.WordWrap = true;
            this.txtState.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtState.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // txtCity
            // 
            this.txtCity.AcceptsReturn = false;
            this.txtCity.AcceptsTab = false;
            this.txtCity.AnimationSpeed = 200;
            this.txtCity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCity.BackColor = System.Drawing.Color.Transparent;
            this.txtCity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCity.BackgroundImage")));
            this.txtCity.BorderColorActive = System.Drawing.Color.Orange;
            this.txtCity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCity.BorderColorHover = System.Drawing.Color.Orange;
            this.txtCity.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCity.BorderRadius = 1;
            this.txtCity.BorderThickness = 1;
            this.txtCity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCity.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCity.DefaultText = "";
            this.txtCity.FillColor = System.Drawing.Color.White;
            this.txtCity.ForeColor = System.Drawing.Color.Black;
            this.txtCity.HideSelection = true;
            this.txtCity.IconLeft = null;
            this.txtCity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCity.IconPadding = 10;
            this.txtCity.IconRight = null;
            this.txtCity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCity.Lines = new string[0];
            this.txtCity.Location = new System.Drawing.Point(105, 105);
            this.txtCity.MaxLength = 32767;
            this.txtCity.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCity.Modified = false;
            this.txtCity.Multiline = false;
            this.txtCity.Name = "txtCity";
            stateProperties5.BorderColor = System.Drawing.Color.Orange;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCity.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCity.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Orange;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCity.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCity.OnIdleState = stateProperties8;
            this.txtCity.Padding = new System.Windows.Forms.Padding(3);
            this.txtCity.PasswordChar = '\0';
            this.txtCity.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCity.PlaceholderText = "";
            this.txtCity.ReadOnly = false;
            this.txtCity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCity.SelectedText = "";
            this.txtCity.SelectionLength = 0;
            this.txtCity.SelectionStart = 0;
            this.txtCity.ShortcutsEnabled = true;
            this.txtCity.Size = new System.Drawing.Size(223, 37);
            this.txtCity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCity.TabIndex = 64;
            this.txtCity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCity.TextMarginBottom = 0;
            this.txtCity.TextMarginLeft = 3;
            this.txtCity.TextMarginTop = 0;
            this.txtCity.TextPlaceholder = "";
            this.txtCity.UseSystemPasswordChar = false;
            this.txtCity.WordWrap = true;
            this.txtCity.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtCity.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // txtStreet
            // 
            this.txtStreet.AcceptsReturn = false;
            this.txtStreet.AcceptsTab = false;
            this.txtStreet.AnimationSpeed = 200;
            this.txtStreet.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStreet.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStreet.BackColor = System.Drawing.Color.Transparent;
            this.txtStreet.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStreet.BackgroundImage")));
            this.txtStreet.BorderColorActive = System.Drawing.Color.Orange;
            this.txtStreet.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStreet.BorderColorHover = System.Drawing.Color.Orange;
            this.txtStreet.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtStreet.BorderRadius = 1;
            this.txtStreet.BorderThickness = 1;
            this.txtStreet.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStreet.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStreet.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtStreet.DefaultText = "";
            this.txtStreet.FillColor = System.Drawing.Color.White;
            this.txtStreet.ForeColor = System.Drawing.Color.Black;
            this.txtStreet.HideSelection = true;
            this.txtStreet.IconLeft = null;
            this.txtStreet.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStreet.IconPadding = 10;
            this.txtStreet.IconRight = null;
            this.txtStreet.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStreet.Lines = new string[0];
            this.txtStreet.Location = new System.Drawing.Point(105, 47);
            this.txtStreet.MaxLength = 32767;
            this.txtStreet.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStreet.Modified = false;
            this.txtStreet.Multiline = false;
            this.txtStreet.Name = "txtStreet";
            stateProperties9.BorderColor = System.Drawing.Color.Orange;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStreet.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStreet.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Orange;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStreet.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStreet.OnIdleState = stateProperties12;
            this.txtStreet.Padding = new System.Windows.Forms.Padding(3);
            this.txtStreet.PasswordChar = '\0';
            this.txtStreet.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtStreet.PlaceholderText = "";
            this.txtStreet.ReadOnly = false;
            this.txtStreet.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStreet.SelectedText = "";
            this.txtStreet.SelectionLength = 0;
            this.txtStreet.SelectionStart = 0;
            this.txtStreet.ShortcutsEnabled = true;
            this.txtStreet.Size = new System.Drawing.Size(223, 37);
            this.txtStreet.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtStreet.TabIndex = 63;
            this.txtStreet.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStreet.TextMarginBottom = 0;
            this.txtStreet.TextMarginLeft = 3;
            this.txtStreet.TextMarginTop = 0;
            this.txtStreet.TextPlaceholder = "";
            this.txtStreet.UseSystemPasswordChar = false;
            this.txtStreet.WordWrap = true;
            this.txtStreet.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtStreet.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // txtLName
            // 
            this.txtLName.AcceptsReturn = false;
            this.txtLName.AcceptsTab = false;
            this.txtLName.AnimationSpeed = 200;
            this.txtLName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLName.BackColor = System.Drawing.Color.Transparent;
            this.txtLName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLName.BackgroundImage")));
            this.txtLName.BorderColorActive = System.Drawing.Color.Orange;
            this.txtLName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLName.BorderColorHover = System.Drawing.Color.Orange;
            this.txtLName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLName.BorderRadius = 1;
            this.txtLName.BorderThickness = 1;
            this.txtLName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtLName.DefaultText = "";
            this.txtLName.FillColor = System.Drawing.Color.White;
            this.txtLName.ForeColor = System.Drawing.Color.Black;
            this.txtLName.HideSelection = true;
            this.txtLName.IconLeft = null;
            this.txtLName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLName.IconPadding = 10;
            this.txtLName.IconRight = null;
            this.txtLName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLName.Lines = new string[0];
            this.txtLName.Location = new System.Drawing.Point(137, 79);
            this.txtLName.MaxLength = 32767;
            this.txtLName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLName.Modified = false;
            this.txtLName.Multiline = false;
            this.txtLName.Name = "txtLName";
            stateProperties13.BorderColor = System.Drawing.Color.Orange;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Orange;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLName.OnIdleState = stateProperties16;
            this.txtLName.Padding = new System.Windows.Forms.Padding(3);
            this.txtLName.PasswordChar = '\0';
            this.txtLName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLName.PlaceholderText = "";
            this.txtLName.ReadOnly = false;
            this.txtLName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLName.SelectedText = "";
            this.txtLName.SelectionLength = 0;
            this.txtLName.SelectionStart = 0;
            this.txtLName.ShortcutsEnabled = true;
            this.txtLName.Size = new System.Drawing.Size(223, 37);
            this.txtLName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLName.TabIndex = 60;
            this.txtLName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLName.TextMarginBottom = 0;
            this.txtLName.TextMarginLeft = 3;
            this.txtLName.TextMarginTop = 0;
            this.txtLName.TextPlaceholder = "";
            this.txtLName.UseSystemPasswordChar = false;
            this.txtLName.WordWrap = true;
            this.txtLName.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtLName.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // txtFName
            // 
            this.txtFName.AcceptsReturn = false;
            this.txtFName.AcceptsTab = false;
            this.txtFName.AnimationSpeed = 200;
            this.txtFName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFName.BackColor = System.Drawing.Color.Transparent;
            this.txtFName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFName.BackgroundImage")));
            this.txtFName.BorderColorActive = System.Drawing.Color.Orange;
            this.txtFName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFName.BorderColorHover = System.Drawing.Color.Orange;
            this.txtFName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtFName.BorderRadius = 1;
            this.txtFName.BorderThickness = 1;
            this.txtFName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtFName.DefaultText = "";
            this.txtFName.FillColor = System.Drawing.Color.White;
            this.txtFName.ForeColor = System.Drawing.Color.Black;
            this.txtFName.HideSelection = true;
            this.txtFName.IconLeft = null;
            this.txtFName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFName.IconPadding = 10;
            this.txtFName.IconRight = null;
            this.txtFName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFName.Lines = new string[0];
            this.txtFName.Location = new System.Drawing.Point(137, 28);
            this.txtFName.MaxLength = 32767;
            this.txtFName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFName.Modified = false;
            this.txtFName.Multiline = false;
            this.txtFName.Name = "txtFName";
            stateProperties17.BorderColor = System.Drawing.Color.Orange;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFName.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFName.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Orange;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFName.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFName.OnIdleState = stateProperties20;
            this.txtFName.Padding = new System.Windows.Forms.Padding(3);
            this.txtFName.PasswordChar = '\0';
            this.txtFName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFName.PlaceholderText = "";
            this.txtFName.ReadOnly = false;
            this.txtFName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFName.SelectedText = "";
            this.txtFName.SelectionLength = 0;
            this.txtFName.SelectionStart = 0;
            this.txtFName.ShortcutsEnabled = true;
            this.txtFName.Size = new System.Drawing.Size(223, 37);
            this.txtFName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFName.TabIndex = 59;
            this.txtFName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFName.TextMarginBottom = 0;
            this.txtFName.TextMarginLeft = 3;
            this.txtFName.TextMarginTop = 0;
            this.txtFName.TextPlaceholder = "";
            this.txtFName.UseSystemPasswordChar = false;
            this.txtFName.WordWrap = true;
            this.txtFName.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtFName.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.Orange;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.Orange;
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 1;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.ForeColor = System.Drawing.Color.Black;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(138, 180);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties21.BorderColor = System.Drawing.Color.Orange;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Orange;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties24;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(223, 37);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 62;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 0;
            this.txtEmail.TextPlaceholder = "";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            this.txtEmail.TextChange += new System.EventHandler(this.txtemail_TextChanged);
            this.txtEmail.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtEmail.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // txtPhone
            // 
            this.txtPhone.AcceptsReturn = false;
            this.txtPhone.AcceptsTab = false;
            this.txtPhone.AnimationSpeed = 200;
            this.txtPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhone.BackColor = System.Drawing.Color.Transparent;
            this.txtPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhone.BackgroundImage")));
            this.txtPhone.BorderColorActive = System.Drawing.Color.Orange;
            this.txtPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhone.BorderColorHover = System.Drawing.Color.Orange;
            this.txtPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPhone.BorderRadius = 1;
            this.txtPhone.BorderThickness = 1;
            this.txtPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPhone.DefaultText = "";
            this.txtPhone.FillColor = System.Drawing.Color.White;
            this.txtPhone.ForeColor = System.Drawing.Color.Black;
            this.txtPhone.HideSelection = true;
            this.txtPhone.IconLeft = null;
            this.txtPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.IconPadding = 10;
            this.txtPhone.IconRight = null;
            this.txtPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.Lines = new string[0];
            this.txtPhone.Location = new System.Drawing.Point(137, 130);
            this.txtPhone.MaxLength = 32767;
            this.txtPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhone.Modified = false;
            this.txtPhone.Multiline = false;
            this.txtPhone.Name = "txtPhone";
            stateProperties25.BorderColor = System.Drawing.Color.Orange;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhone.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Orange;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Black;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnIdleState = stateProperties28;
            this.txtPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txtPhone.PasswordChar = '\0';
            this.txtPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPhone.PlaceholderText = "";
            this.txtPhone.ReadOnly = false;
            this.txtPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhone.SelectedText = "";
            this.txtPhone.SelectionLength = 0;
            this.txtPhone.SelectionStart = 0;
            this.txtPhone.ShortcutsEnabled = true;
            this.txtPhone.Size = new System.Drawing.Size(223, 37);
            this.txtPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhone.TabIndex = 61;
            this.txtPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhone.TextMarginBottom = 0;
            this.txtPhone.TextMarginLeft = 3;
            this.txtPhone.TextMarginTop = 0;
            this.txtPhone.TextPlaceholder = "";
            this.txtPhone.UseSystemPasswordChar = false;
            this.txtPhone.WordWrap = true;
            this.txtPhone.TextChange += new System.EventHandler(this.txtphone_TextChanged);
            this.txtPhone.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtPhone.Leave += new System.EventHandler(this.txtColorChange_Leave);
            // 
            // btnsave
            // 
            this.btnsave.AllowAnimations = true;
            this.btnsave.AllowMouseEffects = true;
            this.btnsave.AllowToggling = false;
            this.btnsave.AnimationSpeed = 200;
            this.btnsave.AutoGenerateColors = false;
            this.btnsave.AutoRoundBorders = false;
            this.btnsave.AutoSizeLeftIcon = true;
            this.btnsave.AutoSizeRightIcon = true;
            this.btnsave.BackColor = System.Drawing.Color.Transparent;
            this.btnsave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnsave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnsave.BackgroundImage")));
            this.btnsave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.ButtonText = "Save";
            this.btnsave.ButtonTextMarginLeft = 0;
            this.btnsave.ColorContrastOnClick = 45;
            this.btnsave.ColorContrastOnHover = 45;
            this.btnsave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnsave.CustomizableEdges = borderEdges2;
            this.btnsave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnsave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnsave.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnsave.ForeColor = System.Drawing.Color.White;
            this.btnsave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnsave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnsave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnsave.IconMarginLeft = 11;
            this.btnsave.IconPadding = 10;
            this.btnsave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnsave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnsave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnsave.IconSize = 25;
            this.btnsave.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnsave.IdleBorderRadius = 15;
            this.btnsave.IdleBorderThickness = 1;
            this.btnsave.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnsave.IdleIconLeftImage = null;
            this.btnsave.IdleIconRightImage = null;
            this.btnsave.IndicateFocus = false;
            this.btnsave.Location = new System.Drawing.Point(534, 421);
            this.btnsave.Name = "btnsave";
            this.btnsave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsave.OnDisabledState.BorderRadius = 15;
            this.btnsave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.OnDisabledState.BorderThickness = 1;
            this.btnsave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsave.OnDisabledState.IconLeftImage = null;
            this.btnsave.OnDisabledState.IconRightImage = null;
            this.btnsave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnsave.onHoverState.BorderRadius = 15;
            this.btnsave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.onHoverState.BorderThickness = 1;
            this.btnsave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnsave.onHoverState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnsave.onHoverState.IconLeftImage = null;
            this.btnsave.onHoverState.IconRightImage = null;
            this.btnsave.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnsave.OnIdleState.BorderRadius = 15;
            this.btnsave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.OnIdleState.BorderThickness = 1;
            this.btnsave.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(52)))), ((int)(((byte)(67)))), ((int)(((byte)(78)))));
            this.btnsave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnsave.OnIdleState.IconLeftImage = null;
            this.btnsave.OnIdleState.IconRightImage = null;
            this.btnsave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnsave.OnPressedState.BorderRadius = 15;
            this.btnsave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.OnPressedState.BorderThickness = 1;
            this.btnsave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(83)))), ((int)(((byte)(96)))));
            this.btnsave.OnPressedState.ForeColor = System.Drawing.Color.LimeGreen;
            this.btnsave.OnPressedState.IconLeftImage = null;
            this.btnsave.OnPressedState.IconRightImage = null;
            this.btnsave.Size = new System.Drawing.Size(118, 44);
            this.btnsave.TabIndex = 67;
            this.btnsave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnsave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnsave.TextMarginLeft = 0;
            this.btnsave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnsave.UseDefaultRadiusAndThickness = true;
            this.btnsave.Click += new System.EventHandler(this.btnsave_Click);
            // 
            // txtCustomerID
            // 
            this.txtCustomerID.AcceptsReturn = false;
            this.txtCustomerID.AcceptsTab = false;
            this.txtCustomerID.AnimationSpeed = 200;
            this.txtCustomerID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCustomerID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCustomerID.BackColor = System.Drawing.Color.Transparent;
            this.txtCustomerID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCustomerID.BackgroundImage")));
            this.txtCustomerID.BorderColorActive = System.Drawing.Color.Orange;
            this.txtCustomerID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCustomerID.BorderColorHover = System.Drawing.Color.Orange;
            this.txtCustomerID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCustomerID.BorderRadius = 1;
            this.txtCustomerID.BorderThickness = 1;
            this.txtCustomerID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCustomerID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCustomerID.DefaultText = "";
            this.txtCustomerID.FillColor = System.Drawing.Color.White;
            this.txtCustomerID.ForeColor = System.Drawing.Color.Black;
            this.txtCustomerID.HideSelection = true;
            this.txtCustomerID.IconLeft = null;
            this.txtCustomerID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerID.IconPadding = 10;
            this.txtCustomerID.IconRight = null;
            this.txtCustomerID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCustomerID.Lines = new string[0];
            this.txtCustomerID.Location = new System.Drawing.Point(159, 79);
            this.txtCustomerID.MaxLength = 32767;
            this.txtCustomerID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCustomerID.Modified = false;
            this.txtCustomerID.Multiline = false;
            this.txtCustomerID.Name = "txtCustomerID";
            stateProperties29.BorderColor = System.Drawing.Color.Orange;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerID.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCustomerID.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Orange;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerID.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Black;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCustomerID.OnIdleState = stateProperties32;
            this.txtCustomerID.Padding = new System.Windows.Forms.Padding(3);
            this.txtCustomerID.PasswordChar = '\0';
            this.txtCustomerID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCustomerID.PlaceholderText = "";
            this.txtCustomerID.ReadOnly = false;
            this.txtCustomerID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCustomerID.SelectedText = "";
            this.txtCustomerID.SelectionLength = 0;
            this.txtCustomerID.SelectionStart = 0;
            this.txtCustomerID.ShortcutsEnabled = true;
            this.txtCustomerID.Size = new System.Drawing.Size(223, 37);
            this.txtCustomerID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCustomerID.TabIndex = 58;
            this.txtCustomerID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCustomerID.TextMarginBottom = 0;
            this.txtCustomerID.TextMarginLeft = 3;
            this.txtCustomerID.TextMarginTop = 0;
            this.txtCustomerID.TextPlaceholder = "";
            this.txtCustomerID.UseSystemPasswordChar = false;
            this.txtCustomerID.WordWrap = true;
            this.txtCustomerID.Click += new System.EventHandler(this.txtColorChange_Click);
            this.txtCustomerID.Leave += new System.EventHandler(this.txtCustomerID_Leave);
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = global::Gear_Store.Properties.Resources.Orange_people_48px;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(16, 2);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(30, 30);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 2;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // btn_Quit
            // 
            this.btn_Quit.Dock = System.Windows.Forms.DockStyle.Right;
            this.btn_Quit.FlatAppearance.BorderSize = 0;
            this.btn_Quit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn_Quit.Image = ((System.Drawing.Image)(resources.GetObject("btn_Quit.Image")));
            this.btn_Quit.Location = new System.Drawing.Point(749, 0);
            this.btn_Quit.Name = "btn_Quit";
            this.btn_Quit.Size = new System.Drawing.Size(59, 35);
            this.btn_Quit.TabIndex = 1;
            this.btn_Quit.UseVisualStyleBackColor = true;
            this.btn_Quit.Click += new System.EventHandler(this.btn_Quit_Click);
            // 
            // Form_CustomerDetails
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(42)))), ((int)(((byte)(45)))));
            this.ClientSize = new System.Drawing.Size(808, 489);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.btnsave);
            this.Controls.Add(this.txtCustomerID);
            this.Controls.Add(this.labelCustomerID);
            this.Controls.Add(this.panelTopBar);
            this.ForeColor = System.Drawing.Color.Black;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form_CustomerDetails";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Form_CustomerDetails";
            this.TopMost = true;
            this.panelTopBar.ResumeLayout(false);
            this.panelTopBar.PerformLayout();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panelTopBar;
        private System.Windows.Forms.Button btn_Quit;
        private System.Windows.Forms.Label labelCustomerID;
        private System.Windows.Forms.Label labelFName;
        private System.Windows.Forms.Label labelLName;
        private System.Windows.Forms.Label labelPhone;
        private System.Windows.Forms.Label labelEmail;
        private System.Windows.Forms.Label labelStreet;
        private System.Windows.Forms.Label labelCity;
        private System.Windows.Forms.Label labelState;
        private Bunifu.UI.WinForms.BunifuTextBox txtCustomerID;
        private Bunifu.UI.WinForms.BunifuTextBox txtFName;
        private Bunifu.UI.WinForms.BunifuTextBox txtLName;
        private Bunifu.UI.WinForms.BunifuTextBox txtPhone;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuTextBox txtState;
        private Bunifu.UI.WinForms.BunifuTextBox txtCity;
        private Bunifu.UI.WinForms.BunifuTextBox txtStreet;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnsave;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
    }
}